# 1장 기초

# 사칙연산


In [4]:
1 + 2

3

In [2]:
3 / 2.4

1.25

In [3]:
3 * 9

27

In [ ]:
# 변수 및 대입연산

In [5]:
a = 1
b = 2
a + b

3

# 출력

In [6]:
a = "Python"
print(a)

Python


# 조건문

In [3]:
a = 1
if a > 1:
   print("a is greater than 1")
else:
   print("a is not greater than 1")

a is not greater than 1


# 반복문

In [7]:
list = [1,2,3]
for i in range(2, 9):
   print(i)

2
3
4
5
6
7
8


In [10]:
for i in range(2,10):
   for j in range(2,10):
       print("%d * %d = %d" % (i, j, i*j))

2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81


In [10]:
i = 0
while i < 3:
     i=i+1
     print(i)

1
2
3


# 함수

In [11]:
def sum(a, b):
     return a+b

print(sum(3,4))

7


# 2장 자료형

## 숫자

### 정수형, 실수형 상수 및 연산

In [14]:
a = 123
a = -178
a = 0

a = 1.2
a = -3.45

In [15]:
a = 3
b = 4
a + b

7

In [16]:
a = 3
b = 4
a * b

12

In [12]:
a = 3
#print(type(a))
b = 4
a / b
#print(type(a/b))

<class 'int'>
<class 'float'>


In [18]:
# x의 y 제곱

a = 3
b = 4
a ** b

81

In [19]:
# 나머지
7 % 3

1

In [20]:
# 몫
7 // 4

1

# 문자열

In [29]:
food = "Python's favorite food is perl"
print(food)

Python's favorite food is perl


In [30]:
say = '"Python is very easy." he says.'
print(say)

"Python is very easy." he says.


In [31]:
food = 'Python\'s favorite food is perl'
print(food)

say = "\"Python is very easy.\" he says."
print(say)

Python's favorite food is perl
"Python is very easy." he says.


In [33]:
# 여러줄 출력
multiline = "Life is too short\nYou need python"
print(multiline)

Life is too short
You need python


In [35]:
# 여러줄 출력
multiline1='''
Life is too short
You need python
'''

print(multiline1)

multiline2="""
Life is too short
You need python
"""

print(multiline2)


Life is too short
You need python


Life is too short
You need python



In [37]:
# 문자열 더하기
head = "Python"
tail = " is fun!"
print(head + tail)

Python is fun!


In [15]:
# 문자열 곱하기
a = "python"
print(a * 2)

print("=" * 50)
print("My Program")
print("=" * 50)
# 연습문제 : 아래와 같이 출력
# *
# **
# ***
# ......
# ***********************************

pythonpython
My Program

*
**
***
****
*****
******
*******
********
*********


## 인덱싱과 슬라이싱

### 인덱싱

In [22]:
# 인덱스는 0부터 시작
a = "Life is too short, You need Python"
print(a[3])
# 연습문제 : 위 문장에서 특정 문자 및 문자열의 개수는?
print(a.count('oo'))

e
1


In [44]:
# 음수 인덱스는 뒷부터 시작. -1이 가장 마지막 문자를 의미
a = "Life is too short, You need Python"
print(a[-1])
print(a[-2])

n
o


### 슬라이싱

In [45]:
a = "Life is too short, You need Python"
print(a[0:4])  # 마지막 5번 인덱스는 포함되지 않음
print(a[5:7])

Life
is


In [46]:
a = "Life is too short, You need Python"

print(a[19:])  # 끝을 지정하지 않으면 마지막까지를 의미함
print(a[:17])   # 시작을 생략하면 처음부터 
print(a[19:-7])      

You need Python
Life is too short
You need


In [47]:
a = "20010331Rainy"
date = a[:8]
weather = a[8:]
print(date)
print(weather)

20010331
Rainy


- 다음과 같은 연산은 에러발생
- 문자열 요소는 수정이 불가능함

In [48]:
a = "Pithon"
a[1] = 'y'

TypeError: 'str' object does not support item assignment

## 문자열 포맷팅

In [50]:
print("I eat %d apples." % 3)
print("I eat %s apples." % "five")

number = 10
day = "three"
print("I ate %d apples. so I was sick for %s days." % (number, day))

I eat 3 apples.
I eat five apples.
I ate 10 apples. so I was sick for three days.


####  기타 문자열 포맷팅은 C언어의 printf와 유사함

## 문자열 관련 함수들

In [51]:
# 특정문자 갯수 세기
a = "hobby"
print(a.count('b'))

2


In [23]:
# 특정문자 위치찾기(fnd와 index)
a = "Python is best choice"

print(a.find('b'))   # 처음 나온 위치(0부터 인덱싱)
print(a.find('k'))   # 존재하지 않으면 -1

#  find와 다른점은 존재하지 않으면 에러발생
print(a.index('b'))   # 처음 나온 위치(0부터 인덱싱)
print(a.index('k'))   # 존재하지 않으면 에러

10
-1
10


ValueError: substring not found

In [28]:
# 문자열 삽입(join)
a= ","
b = a.join('abcd')
print(b)

# 대소문자 바꾸기(upper, lower)
a = "hi"
b = a.upper()
print(b)

# 공백지우기(strip, lstrip, rstrip)
a = " hi "
b = a.strip()
print(b)

#문자열 바꾸기(replace)
a = "  인생은 너무 짧다"
a = a.strip()
print(a)
b = a.replace("인생", "life")
print(b)

# 문자열 나누기(split)
a = "Life is too short"
b = a.split()  # 기본은 공백(스페이스, 탭, 엔터등)을 기준으로 분리
print(b)

a = "a:b:c;d"
b = a.split(":")
print(b)

a,b,c,d
HI
hi
인생은 너무 짧다
life은 너무 짧다
['Life', 'is', 'too', 'short']
['a', 'b', 'c;d']


### 기타 문자열 포맷팅

In [59]:
print("I eat {0} apples".format(3))
print("I eat {0} apples".format("five"))

number = 3
print("I eat {0} apples".format(number))


number = 10
day = "three"
print("I ate {0} apples. so I was sick for {1} days.".format(number, day))

I eat 3 apples
I eat five apples
I eat 3 apples
I ate 10 apples. so I was sick for three days.


# 리스트

In [60]:
d = [1, 2, 'Life', 'is']
d

[1, 2, 'Life', 'is']

### 인덱싱

In [61]:
# 문자열 인덱싱과 동일
a = [1, 2, 3]
print(a)
print(a[0])
print(a[0] + a[2])

print(a[-1])

[1, 2, 3]
1
4
3


In [62]:
# 이중 리스트
a = [1, 2, 3, ['a', 'b', 'c']]
print(a[3])
print(a[3][0])

#삼중 리스트
a = [1, 2, ['a', 'b', ['Life', 'is']]]
print(a[2][2][0])


['a', 'b', 'c']
a
Life


### 슬라이싱

In [33]:
# 문자열 슬라이싱과 동일
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(a[0:2])
print(a[:2])
print(a[2:])
print(a[2:-1])
# 연습문제 : 짝수만 출력하기
for i in a:
    if (i%2 == 0):
        print(i)

[1, 2]
[1, 2]
[3, 4, 5, 6, 7, 8, 9, 10]
[3, 4, 5, 6, 7, 8, 9]
2
4
6
8
10


###  리스트 연산자

In [37]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)
print(a * 3)

print([1,2]+[3])
print(str(a)+"hi")

# 참고:  1 + "hi"는 타입이 불일치하므로 오류임. 방법은 str(1)+"hi"로 타입을이 맞아야 "1hi"가 생성됨

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3]
[1, 2, 3]hi


### 리스트 수정 변경 삭제

In [49]:
a = [1, 2, 3]
a[2] = 4
print(a)

# 1과 2사이의 서브리스트를 새로운 리스트로 대체
a = [1, 2, 3]
a[1:2] = ['a', 'b', 'c']
print(a)

# 인덱스 1번 요소를 대체
a = [1, 2, 3]
a[1] = ['a', 'b', 'c']
print(a)

# 삭제
a = [1, 2, 3]
a[1:3] = [ ]
print(a)

a = [1, 2, 3]
del a[1]
print(a)

# 연습문제 : 1에서 15까지 정수 집합에서 3의 배수의 위치 정보 저장하기
#a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
a = [33, 0, 1, 5, 6, 9, 10, 15, 16, 17, 99, 88]
index = []
for i in range(len(a)):
    if (a[i]%3 ==0):
        index.append(i)
        
print(index)

[1, 2, 4]
[1, 'a', 'b', 'c', 3]
[1, ['a', 'b', 'c'], 3]
[1]
[1, 3]
[0, 1, 4, 5, 7, 10]


## 리스트 관련 함수

In [71]:
# 요소추가
a = [1, 2, 3]
a.append(4)
print(a)

# 정렬
a = [1, 4, 3, 2]
a.sort()
print(a)

# reverse
a = ['a', 'c', 'b']
a.reverse()
print(a)

# 위치반환 (주어진 요소가 위치한 인덱스를 반환. 없으면 오류발생)
a = [1,2,3]
print(a.index(3))
print(a.index(1))

[1, 2, 3, 4]
[1, 2, 3, 4]
['b', 'c', 'a']
2
0


In [51]:
# 요소 삽입(insert(a, b)는 리스트의 a번째 위치에 b를 삽입)
a = [1, 2, 3]
a.insert(0, 4)
print(a)

# 요소 제거(remove(x)는 리스트에서 첫 번째로 나오는 x를 삭제)
a = [1, 2, 3, 1, 2, 3]
a.remove(3)
print(a)

# 갯수 세기(count(x)는 리스트 내에 x가 몇 개 있는지 조사하여 그 개수를 돌려주는 함수)
a = [1,2,3,1]
print(a.count(1))

# 리스트 확장(extend(x)에서 x에는 리스트만 올 수 있으며 원래의 a 리스트에 x 리스트를 더함)
a = [1,2,3]
a.extend([4,5])
print(a)

[4, 1, 2, 3]
[1, 2, 1, 2, 3]
2
[1, 2, 3, 4, 5]


(10, 11)

# 딕셔너리(dictionary)

### 요소 구성 및 추가

In [54]:
a = {1: 'a'}
a[2] = 'b'
print("첫째문장수행결과: {0}".format(a) )

a['name'] = 'pey'
print("둘째문장수행결과: {0}".format(a) )

a[3] = [1,2,3]
print("셋째문장수행결과: {0}".format(a) )

첫째문장수행결과: {1: 'a', 2: 'b'}
둘째문장수행결과: {1: 'a', 2: 'b', 'name': 'pey'}
셋째문장수행결과: {1: 'a', 2: 'b', 3: [1, 2, 3], 'name': 'pey'}


### 요소 삭제

In [55]:
del a[1]
print(a)

{2: 'b', 3: [1, 2, 3], 'name': 'pey'}


###  key로 value 얻기

In [79]:
grade = {'pey': 10, 'julliet': 99}
print(grade['pey'])
print(grade['julliet'])



10
99


In [80]:
dic = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}
print(dic['phone'])

0119993323


### 딕셔너리 함수들

In [56]:
# Key 리스트 만들기(dict_keys라는 객체 생성)
a = {'name': 'pey', 'phone': '0119993323', 'birth': '1118'}
print(a.keys())

# Value 리스트 만들기(dict_values라는 객체 생성)
print(a.values())

# Key, Value 쌍 얻기(items)
# key와 value의 쌍을 튜플로 묶은 값을 dict_items 객체로 돌려준다.
print(a.items())

# Key로 Value얻기(get)
# a['name']과 결과가 동일하나 존재하지 않을 경우 get은 None을 반환하고, a['name']은 오류 발생
a = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}
print(a.get('name'))
print(a['name'])

# 해당 Key가 딕셔너리 안에 있는지 조사하기(in)
print('name' in a)
print('email' in a)

dict_keys(['phone', 'birth', 'name'])
dict_values(['0119993323', '1118', 'pey'])
dict_items([('phone', '0119993323'), ('birth', '1118'), ('name', 'pey')])
pey
pey
True
False


# 집합

In [58]:
# 집합 생성
s1 = set([1,2,3])
print(s1)

s2 = set("Hello UOS")
print(s2)

{1, 2, 3}
{'O', 'l', 'H', 'S', ' ', 'o', 'U', 'e'}


In [65]:
# set을 리스트나 튜플로 변환 가능
s1 = set([1,2,3])

l1 = list(s1)
print(l1)

t1 = tuple(s1)
print(t1)

TypeError: 'list' object is not callable

In [88]:
# 집합연산
s1 = set([1, 2, 3, 4, 5, 6])
s2 = set([4, 5, 6, 7, 8, 9])

print(s1 & s2)  # 교집합
print(s1 | s2)  # 합집합
print(s1 - s2)  # 차집합

{4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3}


In [89]:
# 관련 함수
# 원소 1개 추가
s1 = set([1, 2, 3])
s1.add(4)
print(s1)

# 여러 원소 추가
s1 = set([1, 2, 3])
s1.update([4, 5, 6])
print(s1)

# 원소제거
s1 = set([1, 2, 3])
s1.remove(2)
print(s1)


{1, 2, 3, 4}
{1, 2, 3, 4, 5, 6}
{1, 3}


#  제어문

### if

In [1]:
money = 2000
card = 1
if money >= 3000 or card:
     print("택시를 타고 가라")
else:
     print("걸어가라")

택시를 타고 가라


In [4]:
print(1 in [1, 2, 3])
print(1 not in [1, 2, 3])
print('a' in ('a', 'b', 'c'))
print('j' not in 'python')

True
False
True
True


In [6]:
pocket = ['paper', 'money', 'cellphone']
if 'money' in pocket:
     pass 
else:
     print("카드를 꺼내라")

In [27]:
pocket = ['paper', 'cellphone', 'money']
card = 1
if 'money' in pocket:
      print("택시를 타고가라*")
elif card==1: 
      print("택시를 타고가라**")
else:
      print("걸어가라")

택시를 타고가라*


### while

In [28]:
treeHit = 0
while treeHit < 3:
     treeHit = treeHit +1
     print("나무를 %d번 찍었습니다." % treeHit)
     if treeHit == 10:
         print("나무 넘어갑니다.")
     print(treeHit in [2,4,6,8])
        

나무를 1번 찍었습니다.
False
나무를 2번 찍었습니다.
True
나무를 3번 찍었습니다.
False


### for

In [10]:
test_list = ['one', 'two', 'three'] 
for i in test_list:
     print(i)

one
two
three


In [53]:
a = [(1,2), (3,4), (5,6)]
for (first, last) in a:
     print(first * last)

2
12
30


In [13]:
marks = [90, 25, 67, 45, 80]

number = 0 
for mark in marks: 
    number = number +1 
    if mark >= 60: 
        print("%d번 학생은 합격입니다." % number)
    else: 
        print("%d번 학생은 불합격입니다." % number)

1번 학생은 합격입니다.
2번 학생은 불합격입니다.
3번 학생은 합격입니다.
4번 학생은 불합격입니다.
5번 학생은 합격입니다.


In [31]:
# range(10)은 0부터 10 미만(0~9)의 숫자를 포함하는 range  객체를 생성
a = range(10)   
print(a)

a = range(1, 10)   
print(a)

range(0, 10)
range(1, 10)


In [32]:
sum = 0 
for i in range(5): 
     print(i)
     sum = sum + i 
print(sum)

0
1
2
3
4
10


In [17]:
marks = [90, 25, 67, 45, 80]
for number in range(len(marks)):
    if marks[number] < 60: continue
    print("%d번 학생 축하합니다. 합격입니다." % (number+1))

1번 학생 축하합니다. 합격입니다.
3번 학생 축하합니다. 합격입니다.
5번 학생 축하합니다. 합격입니다.


In [66]:
a = [1,2,3,4]
result = []
for num in a:
    result.append(num*3)
print(result)


# 리스트 안에 for문 포함하기
a = [1,2,3,4]
result = [num * 2 for num in a]
print(result)

[3, 6, 9, 12]
[2, 4, 6, 8]


### 함수

In [22]:
def sum(a, b):
     return a+b

a = 3
b = 4
c = sum(a, b)
print(c)

7


In [23]:
# 입력값이 없는 경우
def say(): 
     return 'Hi' 

a = say()
print(a)

# return값이 없는 경우
def sum(a, b): 
     print("%d, %d의 합은 %d입니다." % (a, b, a+b))

sum(2, 4)

Hi
2, 4의 합은 6입니다.


In [74]:
def sum_many(*args): 
      sum = 0 
      for i in args:
         print(i)
         sum = sum + i 
      return sum 

#result = sum_many(1,2,3)
#print(result)
result = sum_many(1,2,3,4,5)
print(result)

1
2
3
4
5
15


In [31]:
#  여러개의 값을 리턴할 경우, tuple 형태로 리턴함

def sum_and_mul(a,b): 
     return a+b, a*b

sum, mul = sum_and_mul(3,4)
result = sum_and_mul(3,4)
print("[%s, %s]" % (sum, mul))
print(type(sum))
print(result)  #result의 타입은 tuple

[7, 12]
<class 'int'>
(7, 12)


In [76]:
# 인수의 초깃값(default) 설정
def say_myself(name, old, man=True): 
    print("나의 이름은 %s 입니다." % name) 
    print("나이는 %d살입니다." % old) 
    if man: 
        print("남자입니다.")
    else: 
        print("여자입니다.")

say_myself("홍길동", 27)
say_myself("김영희", 25, False)


나의 이름은 홍길동 입니다.
나이는 27살입니다.
남자입니다.
나의 이름은 김영희 입니다.
나이는 25살입니다.
여자입니다.


In [77]:
# 사용자 입력
a = input("당신의 성명을 입력하세요")
print((a+',')*10)


당신의 성명을 입력하세요홍길동
홍길동,홍길동,홍길동,홍길동,홍길동,홍길동,홍길동,홍길동,홍길동,홍길동,


In [33]:
# 프롬프트를 띄워서 사용자 입력 받기
number = input("숫자를 입력하세요: ")
print(number)

숫자를 입력하세요: 3
3


In [82]:
# 큰따옴표(")로 둘러싸인 문자열은 + 연산과 동일하다
print("life" "is" "too short")
print("life"+"is"+"too short") 

# 문자열 띄어쓰기는 콤마로 한다
print("life", "is", "too short")

# 한 줄에 결과값 출력하기
for i in range(10):
     print(i, end=':')

lifeistoo short
lifeistoo short
life is too short
0:1:2:3:4:5:6:7:8:9:

### 파일 입출력

In [35]:
f = open("new.txt", 'w')
for i in range(1, 11):
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()

In [37]:
f = open("new.txt", 'r')
while True:
    line = f.readline()
    if not line: break
    print(line)
f.close()

1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.

4번째 줄입니다.

5번째 줄입니다.

6번째 줄입니다.

7번째 줄입니다.

8번째 줄입니다.

9번째 줄입니다.

10번째 줄입니다.



In [38]:
f = open("new.txt", 'r')
lines = f.readlines()
for line in lines:
    print(line)
f.close()

1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.

4번째 줄입니다.

5번째 줄입니다.

6번째 줄입니다.

7번째 줄입니다.

8번째 줄입니다.

9번째 줄입니다.

10번째 줄입니다.



In [39]:
f = open("new.txt", 'r')
data = f.read()
print(data)
f.close()

1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.



### 클래스

In [1]:
class Calculator:  #클래스는 메소드와 data를 정의해줘야함!  #클래스명 자체가 객체생성함수임 
    def __init__(self):  #메소드1 #특수 함수(꼭 있을 필요는 x)  #객체 생성시 자동 호출되는 함수 
        self.result = 0  #result가 data요소가 됨!  #self는 객체 자신을 의미함 

    def adder(self, num): #메소드2
        self.result += num
        return self.result

cal1 = Calculator()  #클래스명 자체의 함수가 객체생성함수!
cal2 = Calculator()

print(cal1.adder(3))  #self는 객체 자신이니까 넘어감 #인자는 num 한 개!
print(cal1.adder(4))   #3+4 = 7
print(cal2.adder(3))  
print(cal2.adder(7))   #3+7 = 10

3
7
3
10


In [2]:
class Service:
     secret = "영구는 외계인이다."    # 클래스 변수
     def sum(self, a, b):       # 더하기 서비스
         result = a + b
         print("%s + %s = %s입니다." % (a, b, result))

pey = Service()
pey.sum(1,1)

1 + 1 = 2입니다.


In [5]:
class Service:
     secret = "영구는 외계인이다."   # 클래스 변수 #self없이 나오는 변수 #객체에 포함되지 않음 #공장에만 존재한다.ex)생산객체수 공장위치
     def setname(self, name):
         self.name = name         # 객체변수  
     def sum(self, a, b):
         result = a + b
         print("%s님 %s + %s = %s입니다." % (self.name, a, b, result))
        
pey = Service()
pey.setname("홍길동")
pey.sum(1, 1)
print(pey.secret)

pey2 = Service()
pey2.setname("김만식")
pey2.sum(2, 2)
print(pey2.secret)


홍길동님 1 + 1 = 2입니다.
영구는 외계인이다.
김만식님 2 + 2 = 4입니다.
영구는 외계인이다.


In [39]:
class Person:
     def __init__(self, name, birth_year):
         self.name = name
         self.birth_year = birth_year
         print("객체생성")
            
    #ef sum(self, a, b):
    #   result = a + b
    #   print("%s님 %s + %s = %s입니다." % (self.name, a, b, result))
        
     def display(self):
        age = 2018-self.birth_year
        print("[%s, %s년 출생, %s세]" % (self.name, self.birth_year, age))
 
p1 = Person("홍길동", 2000)
p1.display()

객체생성
[홍길동, 2000년 출생, 18세]


# numpy

In [10]:
import numpy as np

a = np.array([1, 2, 3])  # rank=1 shape = (3,)
print (type(a))            
print (a.shape)            
print (a[0], a[1], a[2])   
a[0] = (5)                 # 요소를 변경
print (a)                  

b = np.array([[1,2,3],[4,5,6]])   # rank=2 shape = (2, 3)
print (b.shape)                     
print (b[0, 0], b[0, 1], b[1, 0])   

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [41]:
import numpy as np

a = np.zeros((2,2))  # 모든 값이 0인 배열 생성
print (a)              # 출력 "[[ 0.  0.]
                     #       [ 0.  0.]]"

b = np.ones((1,2))   # 모든 값이 1인 배열 생성
print (b)              # 출력 "[[ 1.  1.]]"

c = np.full((5,3), 7) # 모든 값이 특정 상수인 배열 생성
print (c)               # 출력 "[[ 7.  7.]
                      #       [ 7.  7.]]"

d = np.eye(2)        # 2x2 단위행렬 생성
print (d)              # 출력 "[[ 1.  0.]
                     #       [ 0.  1.]]"

e = np.random.random((5,3)) # (0~1)사이의 임의의 값으로 채워진 5*3 행렬 생성
print (e)                   # 임의의 값 출력 "[[ 0.91940167  0.08143941]
                            #                  [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0.]
 [0. 1.]]
[[0.60951695 0.67543757 0.14834341]
 [0.2571669  0.23821022 0.74448984]
 [0.17928939 0.77071645 0.67500726]
 [0.12857983 0.26730316 0.74158417]
 [0.48481087 0.2781092  0.76038075]]


In [83]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 슬라이싱을 이용하여 첫 두 행과 1열, 2열로 이루어진 부분배열
# b는 shape가 (2,2)인 배열
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조. 즉 슬라이싱된 배열을 수정하면
# 원본 배열 역시 수정됨  (reference 연결되어 있음0)
print (a[0, 1])   # 출력 "2"
b[0, 0] = 77    # b[0, 0]은 a[0, 1]과 같은 데이터
print (a[0, 1])   # 출력 "77"

[[2 3]
 [6 7]]
2
77


In [16]:
import numpy as np

# 아래와 같은 요소를 가지는 rank가 2이고 shape가 (3, 4)인 배열 생성
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 배열의 중간 행에 접근하는 두 가지 방법이 있습니다.
# 정수 인덱싱과 슬라이싱을 혼합해서 사용하면 낮은 rank의 배열이 생성되지만,
# 슬라이싱만 사용하면 원본 배열과 동일한 rank의 배열이 생성.
row_r1 = a[1, :]    # 배열a의 두 번째 행을 rank가 1인 배열로
row_r2 = a[1:2, :]  # 배열a의 두 번째 행을 rank가 2인 배열로
print (row_r1, row_r1.shape)  # 출력 "[5 6 7 8] (4,)"
print (row_r2, row_r2.shape) # 출력 "[[5 6 7 8]] (1, 4)"

# 행이 아닌 열의 경우에도 마찬가지
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)  # 출력 "[ 2  6 10] (3,)"
print (col_r2, col_r2.shape)  # 출력 "[[ 2]
                            #       [ 6]
                            #       [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [17]:
import numpy as np

x = np.array([1, 2])  # Numpy가 자료형을 추측해서 선택
print (x.dtype)         # 출력 "int64"

x = np.array([1.0, 2.0])  # Numpy가 자료형을 추측해서 선택
print (x.dtype)             # 출력 "float64"

x = np.array([1, 2], dtype=np.int64)  # 특정 자료형을 명시적으로 지정
print (x.dtype)                         # 출력 "int64"

int32
float64
int64


In [19]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# [[ 6.0  8.0]
#  [10.0 12.0]]
print (x + y)
print (np.add(x, y))

# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print (x - y)
print (np.subtract(x, y))

# [[ 5.0 12.0]
#  [21.0 32.0]]
print (x * y)
print (np.multiply(x, y))

# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [24]:
import numpy as np

x = np.array([[1,2],[3,4]])

print (np.sum(x))  # 모든 요소를 합한 값을 연산; 출력 "10"
print (np.sum(x, axis=0))  # 각 열에 대한 합을 연산; 출력 "[4 6]"
print (np.sum(x, axis=1))  # 각 행에 대한 합을 연산; 출력 "[3 7]"

10
[4 6]
[3 7]


In [25]:
import numpy as np

x = np.array([[1,2], [3,4]])
print (x)    # 출력 "[[1 2]
           #          [3 4]]"
print (x.T)  # 출력 "[[1 3]
           #          [2 4]]"

# rank 1인 배열을 전치할 경우 아무 일도 일어나지 않음
v = np.array([1,2,3])
print (v)    # 출력 "[1 2 3]"
print (v.T)  # 출력 "[1 2 3]"

# 2차원 배열
v = np.array([[1,2,3]])
print (v)    # 출력 "[1 2 3]"
print (v.T)  # 출력 "[1 2 3]"


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [33]:
x = np.array([1, 2, 3, 4])
y = 3

print(x[x%2] * 3)  # broadcasting
#print(x + 3)
#print(x / 3)

[1 0 1 0]
[6 3 6 3]


In [14]:
# 차원 변경 함수 (reshape)
import numpy as np
x = np.array([[1, 2, 3],[4, 5, 6]])
y = x.reshape((3, 2))

#print(x)
print(y)

[[1 2]
 [3 4]
 [5 6]]


# Pandas

In [65]:
import pandas as pd

kakao = pd.Series([92600, 92400, 92100, 94300, 92300])
print(kakao)

print(kakao[0])
print(kakao[2])
print(kakao[4])

0    92600
1    92400
2    92100
3    94300
4    92300
dtype: int64
92600
92100
92300


In [42]:
import pandas as pd

mine   = pd.Series([10, 20, 30], index=['naver', 'sk', 'kt'])

for idx in mine.index:
    print(mine[idx])

for price in mine.values:
    print(price)


10
20
30
10
20
30


In [2]:
import pandas as pd

raw_data = {'col0': [1, 2, 3, 4],
                        'col1': [10, 20, 30, 40],
                        'col2': [100, 200, 300, 400]}

data = pd.DataFrame(raw_data)
print(data)
print(data['col1'])

   col0  col1  col2
0     1    10   100
1     2    20   200
2     3    30   300
3     4    40   400
0    10
1    20
2    30
3    40
Name: col1, dtype: int64


In [ ]:
print(type(data['col0']))  # dataframe의 각 column은 series 객체

In [15]:
import pandas as pd
# 키, 몸무게, 유형 데이터프레임 생성하기
tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2 ],
    "height": [ 170,  180,  155,  143,  154  ],
    "type":   [ "f", "n", "n", "t", "t"]
})
# 몸무게 목록 추출하기
print("몸무게 목록")
print(tbl["weight"][2:4])
# 몸무게와 키 목록 추출하기
print("몸무게와 키 목록")
print(tbl[["weight","height"]])  # 2개 이상의 column을 추출할 경우 리스트를 이용

몸무게 목록
2    65.5
3    45.9
Name: weight, dtype: float64
몸무게와 키 목록
   weight  height
0    80.0     170
1    70.4     180
2    65.5     155
3    45.9     143
4    51.2     154


In [3]:
import pandas as pd

tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2 ],
    "height": [ 170,  180,  155,  143,  154  ],
    "type":   [ "f", "n", "n", "t", "t"]
})

print(tbl[2:4]) # row 조건
print(tbl.iloc[2:4, :])  # 위와 동일한 결과(iloc)
print("\n")
print(tbl["weight"][2:4])  # column과 row조건이 모두 포함
                           # tbl[2:4]["weight"]와 같이 기술해도 결과는 동일

   height type  weight
2     155    n    65.5
3     143    t    45.9
   height type  weight
2     155    n    65.5
3     143    t    45.9


2    65.5
3    45.9
Name: weight, dtype: float64


In [4]:
import pandas as pd
# 키, 몸무게, 유형 데이터프레임 생성하기
tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]
})
print("--- height가 160 이상인 것")
print(tbl[tbl.height >= 160])
print("--- gender가 m 인 것")
print(tbl[tbl.gender == "m"])
print(tbl[tbl.height < 160])

--- height가 160 이상인 것
  gender  height  weight
0      f     170    80.0
1      m     180    70.4
5      m     160    72.5
--- gender가 m 인 것
  gender  height  weight
1      m     180    70.4
2      m     155    65.5
5      m     160    72.5
  gender  height  weight
2      m     155    65.5
3      f     143    45.9
4      f     154    51.2


In [80]:
import pandas as pd

tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]
})
print("--- 키로 정렬")
print(tbl.sort_values(by="height"))
print("--- 몸무게로 정렬")
print(tbl.sort_values(by="weight", ascending=False))

--- 키로 정렬
  gender  height  weight
3      f     143    45.9
4      f     154    51.2
2      m     155    65.5
5      m     160    72.5
0      f     170    80.0
1      m     180    70.4
--- 몸무게로 정렬
  gender  height  weight
0      f     170    80.0
5      m     160    72.5
1      m     180    70.4
2      m     155    65.5
4      f     154    51.2
3      f     143    45.9


In [8]:
import pandas as pd

tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]})
print(tbl)

tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]}, columns = ["weight", "height", "gender"])


print(tbl)

  gender  height  weight
0      f     170    80.0
1      m     180    70.4
2      m     155    65.5
3      f     143    45.9
4      f     154    51.2
5      m     160    72.5
   weight  height gender
0    80.0     170      f
1    70.4     180      m
2    65.5     155      m
3    45.9     143      f
4    51.2     154      f
5    72.5     160      m


In [9]:
import pandas as pd

tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]
})
# 키와 몸무게 정규화하기
# 최댓값과 최솟값 구하기
def norm(tbl, key):
    c = tbl[key]
    v_max = c.max()
    v_min = c.min()
    print(key, "=", v_min, "-", v_max)
    tbl[key] = (c - v_min) / (v_max - v_min)
norm(tbl, "weight")
norm(tbl, "height")
print(tbl)

weight = 45.9 - 80.0
height = 143 - 180
  gender    height    weight
0      f  0.729730  1.000000
1      m  1.000000  0.718475
2      m  0.324324  0.574780
3      f  0.000000  0.000000
4      f  0.297297  0.155425
5      m  0.459459  0.780059


In [48]:
import pandas as pd

tbl = pd.DataFrame({
    "x": [1, 2, 3],
    "y": [4, 5, 6],
    "z": [7, 8, 9]
})

n = tbl.as_matrix()
#print(n)
print(n[:1,:2])

[[1 4]]


c:\users\hjkim\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


In [20]:
tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]
})

print(tbl.shape)


<bound method NDFrame.rank of   gender  height  weight
0      f     170    80.0
1      m     180    70.4
2      m     155    65.5
3      f     143    45.9
4      f     154    51.2
5      m     160    72.5>
(6, 3)
