# Tensorflow 기초

In [1]:
# 간단한 메시지 출력하기
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!') #문자열 상수 생성 #노드에 해당 #tensorflow의 tensor변수임! 일반적인 파이썬 변수가 아니라 tensor를 만들어서 flow시켜줘야 함!
sess = tf.Session()  #tensor가 flow하기 위한 객체 = Session  
print(sess.run(hello))
sess.close()

b'Hello, TensorFlow!'


In [1]:
# 경고가 발생할 경우 다음 코드 삽입
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))
sess.close()

b'Hello, TensorFlow!'


In [3]:
import tensorflow as tf

# 상수 정의 (상수 객체 정의)
# a와 b는 변수가 아니라 a와 b를 가리키는 reference
a = tf.constant(1234)
b = tf.constant(5000)
# add 연산 정의 
# add_op는 변수가 아니라 add연산자를 가리키는 reference
add_op = a + b

# 세션 시작하기(계산을 실행하기 위한 세션 실행) 
sess = tf.Session()

# 세션 객체의 run method로 add_op객체의 값 계산하기
res = sess.run(add_op) 
print(res)

# 세션을 열었으면 반드시 close해야함
sess.close()

6234


In [1]:
import tensorflow as tf

tensor_a = tf.constant(3, name="a")
tensor_b = tf.constant(3, name="b")
tensor_c = tf.constant(3, name="c")

tensor_d = tensor_a * tensor_b
tensor_e = tensor_d + tensor_c

sess = tf.Session()
sess.run(tensor_e)
sess.run(tensor_a)
tf.get_default_graph().get_operations()
print(tensor_a.op.node_def)
print(tensor_b.op.node_def)
print(tensor_e.op.node_def)
print(tensor_d.op.node_def)
print(tensor_e.op.node_def)

name: "a"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
      }
      int_val: 3
    }
  }
}

name: "b"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
      }
      int_val: 3
    }
  }
}

name: "add"
op: "Add"
input: "mul"
input: "c"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}

name: "mul"
op: "Mul"
input: "a"
input: "b"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}

name: "add"
op: "Add"
input: "mul"
input: "c"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}



In [15]:
import tensorflow as tf
# 상수 정의하기 
a = tf.constant(2) #2를 담고있는 a라는 객체 
b = tf.constant(3)
c = tf.constant(4)
# 연산 정의하기 
calc1_op = a + b * c
calc2_op = (a + b) * c
# 세션 시작하기 
sess = tf.Session()
res1 = sess.run(calc1_op) # 식 평가하기
print(res1)
res2 = sess.run(calc2_op) # 식 평가하기
print(res2)
sess.close()

14
20


In [1]:
import tensorflow as tf
# 상수 정의하기 
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)
# 연산 정의하기 
calc1_op = a + b * c
calc2_op = (a + b) * c
# 세션 시작하기
# 다음과 같이 실행할 경우 sess.close 생략 가능

with tf.Session()  as sess:
   res1 = sess.run(calc1_op) # 식 평가하기
   print(res1)
   res2 = sess.run(calc2_op) # 식 평가하기
   print(res2)

14
20


In [19]:
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!') 

with tf.Session()  as sess:
    # hello는 bytes type
    byte_hello = sess.run(hello)
    print(byte_hello)
    # string type으로 변환 가능
    str_hello = byte_hello.decode(encoding='utf-8')
    print(str_hello)

b'Hello, TensorFlow!'
Hello, TensorFlow!


In [30]:
import tensorflow as tf

# 변수 정의하기 (10은 초기값. 변수는 반드시 초기값을 부여해야함)
v = tf.Variable(10)

with tf.Session() as sess:
   #변수를 사용할 경우 반드시 다음과 같은 초기화를 해야 실행이 됨 
   sess.run(tf.global_variables_initializer())
   result = sess.run(v)
   print(result)

10


In [5]:
import tensorflow as tf

a = tf.Variable(1)

# 변수객체 a을 10으로 변경하는 assign 연산을 정의
# b는 assign 연산을 기르키는 reference
b = tf.assign(a, 10) 

print ("a: ", a) # 객체정보 출력
print ("b: ", b) # 객체정보 출력

with tf.Session() as sess:
   sess.run(tf.global_variables_initializer())

   print (sess.run(a)) # a만 실행(a==1)
   print (sess.run(b)) # b실행(assign 연산 실행) (b==10, a==10)
   print (sess.run(a)) # b를 실행한 이후이므로 a는 변경된 10을 출력


a:  <tf.Variable 'Variable_4:0' shape=() dtype=int32_ref>
b:  Tensor("Assign_4:0", shape=(), dtype=int32_ref)
1
10
10


In [2]:
import tensorflow as tf

a = tf.Variable(1) #a는 tensor 객체
b = a * 3  #a는 tensor 3은 파이썬 상수 --> 연산 시행하면 파이썬 상수가 tensor객체로 바뀌어서 알아서 계산됨 
c = tf.assign(a, tf.add(a, 1))


sess = tf.Session()
sess.run(tf.global_variables_initializer())

print (sess.run(a)) # a <- 1
print (sess.run(c)) # a <- 2, c <- 2 (add(1,1))
print (sess.run(b)) # b <- 2 * 3
print (sess.run(a)) # a <- 2

1
2
6
2


### tensorboard

In [1]:
import tensorflow as tf

a = tf.Variable(1)
b = a * 3
c = tf.assign(a, tf.add(a, 1))


sess = tf.Session()

# tensorboard로 표현하기 위해 log 기록
# log_dir 폴더에 로그가 기록됨
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)

sess.run(tf.global_variables_initializer())

print (sess.run(a)) # a <- 1
print (sess.run(c)) # a <- 2, c <- 2 
print (sess.run(b)) # b <- 2 * 3
print (sess.run(a)) # a <- 2

1
2
6
2


In [4]:
import tensorflow as tf

a = tf.Variable(1, name="a")
b = a * 3
c = tf.add(a, 1, name='c')
d = tf.assign(a, c, name="d")


sess = tf.Session()


tw = tf.summary.FileWriter("log_dir", graph=sess.graph)

sess.run(tf.global_variables_initializer())

print (sess.run(a)) # a <- 1
print (sess.run(b)) 
print (sess.run(d)) 
print (sess.run(a)) # a <- 2

1
3
2
2


In [5]:
import tensorflow as tf
# 상수 정의하기 
a = tf.constant(120)
b = tf.constant(130)
c = tf.constant(140)
# 변수 정의하기 
v = tf.Variable(0)
v = tf.assign(v, 1)
j = v+1
# 데이터 플로우 그래프 정의하기 
k=a  #k는 a라는 상수를 가리키는 변수
v=1  #v는 더 이상 tensor를 가리키지 않음. 일반 변수임
print(v) #실행됨
k=1
print(k) #실행됨
print(a) # 타입만 출력되고 실제값은 안나옴. session을 실행해야 결과 출력됨

o = tf.add(1,1)  # 1은 파이썬 상수이고 o는 tensor임. 
                 # tf 연산자에 피연산자가 일반 상수가 올 수 있음. 단 결과는 텐서로 만들어짐
                 # o = 1+1은 o가 텐서가 아님. 파이썬 변수임. 단 두개의 1중에 하나라도 텐서이면 o는 텐서가 됨
# 세션 실행하기 
sess = tf.Session()
#sess.run(v)
# v의 내용 출력하기 
#print( sess.run(k) ) # error: k는 tensor가 아님
#print( sess.run(v) ) # error: v는 tensor가 아님
print( sess.run(j) ) # 정상
print(sess.run(o)) # 정상

1
1
Tensor("a_3:0", shape=(), dtype=int32)
2
2


In [1]:
import tensorflow as tf

x = tf.Variable(0)
y = tf.assign(x, 1)  
x=x+3

with tf.Session() as sess:
    tw = tf.summary.FileWriter("log_dir", graph=sess.graph)
    
    # 초기화 안하면 x변수가 0으로 초기화가 안됨
    sess.run(tf.global_variables_initializer()) 
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(x))

3
1
4


In [ ]:
import tensorflow as tf
# 플레이스홀더 정의하기 --- (※1)
a = tf.placeholder(tf.int32, [3]) # 정수 자료형 3개를 가진 배열
# 배열을 모든 값을 2배하는 연산 정의하기 --- (※2)
b = tf.constant(2)
x2_op = a * b
# 세션 시작하기 --- (※3)
sess = tf.Session()
# 플레이스홀더에 값을 넣고 실행하기 --- (※4)
r1 = sess.run(x2_op, feed_dict={ a:[1, 2, 3] })
print(r1)
r2 = sess.run(x2_op, feed_dict={ a:[10, 20, 10] })
print(r2)

### placeholder

In [4]:
import tensorflow as tf

# float type의 placeholder 정의
a = tf.placeholder("float")  #placeholder: tensor 객체를 담을 수 있는 빈 메모리 공간  #미리 값 설정 x, run할 때서야 값을 넣음 
b = tf.placeholder("float")

y = tf.add(a, b)

with tf.Session() as sess:
       result = sess.run(y, feed_dict={a: 3, b: 3})  # placeholder에 값을 대입하여 연산 #sess.run(노드명, feed_dict:데이터) -> key: value
       print(result)

6.0


In [2]:
import tensorflow as tf

a = tf.placeholder(tf.int32, [3]) #3개의 정수 넣겠다 

b = tf.constant(2)
x2_op = a * b

with tf.Session() as sess:
    r1 = sess.run(x2_op, feed_dict={ a:[1, 2, 3] })  #값 여러개 넣고 싶을 때 값으로 array넣으면 됨!
    print(r1)
    r2 = sess.run(x2_op, feed_dict={ a:[10, 20, 10] })
    print(r2)

[2 4 6]
[20 40 20]


In [5]:
import tensorflow as tf

# 플레이스홀더 정의
# 배열의 크기를 None으로 지정. 1차원 배열이란 것만 명시
a = tf.placeholder(tf.int32, [None])  #개수를 모를 경우가 대부분 --> None으로 표시 
# 배열의 모든 값을 10배하는 연산 정의하기 

b = tf.constant(10)
x10_op = a * b

with tf.Session() as sess:
     # 플레이스홀더에 값을 넣어 실행
     r1 = sess.run(x10_op, feed_dict={a: [1,2,3,4,5]})
     print(r1)
     r2 = sess.run(x10_op, feed_dict={a: [10,20]})
     print(r2)

[10 20 30 40 50]
[100 200]
