# Regression

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

#H(x) = Wx + b 에서 W와 b를 알아내야 해!
import tensorflow as tf
tf.set_random_seed(777)  
x_train = [1, 2, 3] #x와 y 미리 세팅 --> 대부분은 이렇지 않고 placeholder만들어 놓고 run할 때 데이터 넣음 
y_train = [1, 2, 3]


W = tf.Variable(tf.random_normal([1]), name='weight') #임의의 w를 넣어줌 #1개의 난수값 
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x_train * W + b  

cost = tf.reduce_mean(tf.square(hypothesis - y_train)) #예측값과 정답 간 차이 제곱 평균 

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)  #optimizer 객체 안에 cost를 minimize하기 위한 코드 #train이라는 tensor가 optimizer객체에 대한 cost와 만나 만들어짐

sess = tf.Session()
sess.run(tf.global_variables_initializer())  

for step in range(2001):
    sess.run(train)  #train을 run하면 cost, optimizer, hypothesis, y_train, W, b이 flow내에서 다 작동 
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W), sess.run(b)) #W는 거의 1에, b는 거의 0에 가까움!

Instructions for updating:
Colocations handled automatically by placer.
0 2.823292 [2.1286771] [-0.8523567]
20 0.19035067 [1.533928] [-1.0505961]
40 0.15135698 [1.4572546] [-1.0239124]
60 0.1372696 [1.4308538] [-0.9779527]
80 0.12466871 [1.4101374] [-0.93219817]
100 0.113226034 [1.3908179] [-0.8884077]
120 0.10283363 [1.3724468] [-0.8466577]
140 0.09339521 [1.3549428] [-0.80686814]
160 0.084823035 [1.3382617] [-0.7689483]
180 0.07703761 [1.3223647] [-0.73281056]
200 0.06996683 [1.3072149] [-0.6983712]
220 0.06354501 [1.2927768] [-0.6655505]
240 0.057712615 [1.2790174] [-0.63427216]
260 0.0524155 [1.2659047] [-0.6044637]
280 0.04760464 [1.2534081] [-0.57605624]
300 0.043235257 [1.2414987] [-0.5489836]
320 0.039266944 [1.2301493] [-0.5231833]
340 0.03566285 [1.2193329] [-0.49859545]
360 0.032389563 [1.2090251] [-0.47516325]
380 0.029416703 [1.1992016] [-0.45283225]
400 0.026716745 [1.18984] [-0.4315508]
420 0.024264557 [1.1809182] [-0.41126958]
440 0.022037461 [1.1724157] [-0.39194146]
4

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

# PlaceHolder를 이용한 linear regression  testing하기
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Now we can use X and Y in place of x_data and y_data
# # placeholders for a tensor that will be always fed using feed_dict
X = tf.placeholder(tf.float32, shape=[None])  # [None]은 1차원이며 갯수는 임의 #몇개 넣을지 모름 
Y = tf.placeholder(tf.float32, shape=[None])

hypothesis = X * W + b   # Our hypothesis XW+b

cost = tf.reduce_mean(tf.square(hypothesis - Y)) # cost/loss function

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Fit the line
for step in range(2001):
    cost_val, W_val, b_val, _ =  sess.run([cost, W, b, train],  feed_dict={X: [1, 2, 3], Y: [1, 2, 3]})   
    if step % 20 == 0:
        print(step, cost_val, W_val, b_val)  #작동되면서 동시에 각각을 알고자 함

# Testing our model
print(sess.run(hypothesis, feed_dict={X: [5]}))
print(sess.run(hypothesis, feed_dict={X: [2.5]}))
print(sess.run(hypothesis, feed_dict={X: [1.5, 3.5]}))

'''
[ 5.0110054]
[ 2.50091505]
[ 1.49687922  3.50495124]
'''


# Fit the line with new training data
for step in range(2001):  #역시 run할 때 데이터 넣어줌 
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train], feed_dict={X: [1, 2, 3, 4, 5], Y: [2.1, 3.1, 4.1, 5.1, 6.1]})
    if step % 20 == 0:
        print(step, cost_val, W_val, b_val)  #W는 1, b는 1.1

# Testing our model
print(sess.run(hypothesis, feed_dict={X: [5]}))  #각 데이터 넣었을 때 예측값 맞는지! 
print(sess.run(hypothesis, feed_dict={X: [2.5]}))
print(sess.run(hypothesis, feed_dict={X: [1.5, 3.5]}))



0 3.5240757 [2.1286771] [-0.8523567]
20 0.19749945 [1.533928] [-1.0505961]
40 0.15214379 [1.4572546] [-1.0239124]
60 0.1379325 [1.4308538] [-0.9779527]
80 0.12527025 [1.4101374] [-0.93219817]
100 0.11377233 [1.3908179] [-0.8884077]
120 0.10332986 [1.3724468] [-0.8466577]
140 0.093845844 [1.3549428] [-0.80686814]
160 0.08523229 [1.3382617] [-0.7689483]
180 0.07740932 [1.3223647] [-0.73281056]
200 0.07030439 [1.3072149] [-0.6983712]
220 0.06385162 [1.2927768] [-0.6655505]
240 0.05799109 [1.2790174] [-0.63427216]
260 0.05266844 [1.2659047] [-0.6044637]
280 0.047834318 [1.2534081] [-0.57605624]
300 0.043443877 [1.2414987] [-0.5489836]
320 0.0394564 [1.2301493] [-0.5231833]
340 0.035834935 [1.2193329] [-0.49859545]
360 0.032545824 [1.2090251] [-0.47516325]
380 0.029558638 [1.1992016] [-0.45283225]
400 0.026845641 [1.18984] [-0.4315508]
420 0.024381675 [1.1809182] [-0.41126958]
440 0.02214382 [1.1724157] [-0.39194146]
460 0.020111356 [1.1643128] [-0.37352163]
480 0.018265454 [1.1565907] [-0.

### Multi-variable linear regression with TF

In [11]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
tf.set_random_seed(777) 

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.00001)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(10001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 1000 == 0:
        print(step, " => Cost: ", cost_val, ", Prediction: ", hy_val)

#여기서  hy_val(즉, hyperthesis는 결정된 W와 b에 실제 x1, x2, x3를 넣어서 산된 hyperthesis 값들
# 즉, 추정된 값들을 출력해준다.

0  => Cost:  4010.8657 , Prediction:  [217.9278  244.27563 249.96626 271.19232 182.55971]
1000  => Cost:  35.18929 , Prediction:  [159.53105 179.0462  183.11668 198.6645  133.81656]
2000  => Cost:  20.63159 , Prediction:  [157.53055 180.41989 182.50662 198.20045 135.63852]
3000  => Cost:  12.160946 , Prediction:  [156.00714 181.46652 182.04263 197.84273 137.03069]
4000  => Cost:  7.2307067 , Prediction:  [154.84747 182.26369 181.69005 197.56616 138.09502]
5000  => Cost:  4.3597336 , Prediction:  [153.96518 182.87065 181.42238 197.35161 138.90927]
6000  => Cost:  2.686568 , Prediction:  [153.29437 183.33261 181.21945 197.18442 139.53275]
7000  => Cost:  1.7101882 , Prediction:  [152.78477 183.68394 181.06581 197.0534  140.01067]
8000  => Cost:  1.1392128 , Prediction:  [152.39807 183.95102 180.94981 196.9501  140.37753]
9000  => Cost:  0.8041728 , Prediction:  [152.10509 184.15381 180.86244 196.86801 140.65965]
10000  => Cost:  0.6064979 , Prediction:  [151.88348 184.30757 180.79689 196

### Matrix이용

In [13]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
tf.set_random_seed(777)

#Feature가 두개 이상일 경우에는 matrix를 이용함
#아래는 feature가 3개이고 5개의 입력이 있는 경우임

# X는 5*3 (3개의 feature를 가진 데이터가 5개), 
# Y는 5*1 (1개의 종속변수가 5개) matrix로 정의
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

# placeholders for a tensor that will be always fed.
# X, T, 둘다 2차원 배열로 정의, X의 3은 feature 수

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])


#W와 b는 shape만 정의함
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
# 행렬릐 곱을 연산하는데 X*W를 해야함. W*X는 안됨
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(10001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0:
        print(step, " => Cost: ", cost_val, ", Prediction: ", hy_val)


0  => Cost:  9871.248 , Prediction:  [[62.019836]
 [79.533295]
 [75.953835]
 [82.640434]
 [61.62219 ]]
1000  => Cost:  0.5992774 , Prediction:  [[150.41331]
 [185.32433]
 [180.4276 ]
 [196.36623]
 [142.23805]]
2000  => Cost:  0.48081964 , Prediction:  [[150.59787]
 [185.19936]
 [180.4861 ]
 [196.39305]
 [142.0872 ]]
3000  => Cost:  0.40999126 , Prediction:  [[150.74017]
 [185.10336]
 [180.53163]
 [196.41086]
 [141.97406]]
4000  => Cost:  0.36696422 , Prediction:  [[150.85016]
 [185.02942]
 [180.5672 ]
 [196.4218 ]
 [141.88959]]
5000  => Cost:  0.34018153 , Prediction:  [[150.93552]
 [184.97238]
 [180.59517]
 [196.42761]
 [141.82697]]
6000  => Cost:  0.32294482 , Prediction:  [[151.00203]
 [184.92822]
 [180.61734]
 [196.42958]
 [141.78096]]
7000  => Cost:  0.31131822 , Prediction:  [[151.05414]
 [184.89389]
 [180.63503]
 [196.4286 ]
 [141.74757]]
8000  => Cost:  0.30305365 , Prediction:  [[151.09523]
 [184.8671 ]
 [180.64932]
 [196.42554]
 [141.72379]]
9000  => Cost:  0.29680586 , Predi

### csv파일 입력을 통한 MVRL

In [14]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
print(xy)
print("----------------")
print(xy[:, 0:-1])
print("----------------")
print(xy[:,-1])

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]
----------------
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.

In [7]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
#print(x_data.shape, x_data, len(x_data))
#print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# Ask my score
print("Your score will be ",     sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

0 Cost:  163425.31 
Prediction:
 [[-227.74287]
 [-272.6442 ]
 [-269.39563]
 [-291.12766]
 [-209.50986]
 [-150.79063]
 [-214.81425]
 [-154.95331]
 [-251.76035]
 [-228.053  ]
 [-208.96584]
 [-204.68225]
 [-280.6425 ]
 [-236.46179]
 [-215.38509]
 [-274.60327]
 [-227.6153 ]
 [-256.63962]
 [-268.0793 ]
 [-239.5606 ]
 [-252.57571]
 [-253.6167 ]
 [-241.54851]
 [-234.9977 ]
 [-283.81717]]
10 Cost:  16.909573 
Prediction:
 [[149.72728]
 [181.03552]
 [177.62506]
 [195.70767]
 [136.4971 ]
 [104.2993 ]
 [149.59424]
 [115.19038]
 [172.22957]
 [164.6553 ]
 [142.12573]
 [141.49785]
 [181.19585]
 [147.46667]
 [150.69727]
 [185.77142]
 [138.0297 ]
 [180.6846 ]
 [172.21886]
 [154.4011 ]
 [174.75186]
 [171.992  ]
 [165.87625]
 [145.592  ]
 [186.37206]]
20 Cost:  9.086913 
Prediction:
 [[152.33939]
 [184.16983]
 [180.71634]
 [199.07062]
 [138.88928]
 [106.05664]
 [152.10748]
 [117.04806]
 [175.1531 ]
 [167.35458]
 [144.54936]
 [143.8839 ]
 [184.39323]
 [150.12958]
 [153.22089]
 [188.94897]
 [140.56863]
 [

400 Cost:  8.348308 
Prediction:
 [[152.50192 ]
 [184.19044 ]
 [180.83739 ]
 [199.0731  ]
 [138.96811 ]
 [105.894356]
 [151.9657  ]
 [116.74735 ]
 [174.97359 ]
 [166.88647 ]
 [144.49353 ]
 [143.702   ]
 [184.64796 ]
 [150.51476 ]
 [153.038   ]
 [188.86267 ]
 [141.03836 ]
 [183.48837 ]
 [175.55884 ]
 [157.3848  ]
 [177.55444 ]
 [174.8332  ]
 [168.60149 ]
 [148.69994 ]
 [189.7329  ]]
410 Cost:  8.331751 
Prediction:
 [[152.50534]
 [184.19049]
 [180.8398 ]
 [199.07259]
 [138.96971]
 [105.89023]
 [151.96175]
 [116.7396 ]
 [174.96886]
 [166.87477]
 [144.49174]
 [143.69725]
 [184.6536 ]
 [150.52365]
 [153.03307]
 [188.86009]
 [141.04941]
 [183.48259]
 [175.56532]
 [157.39046]
 [177.55037]
 [174.83044]
 [168.59883]
 [148.71072]
 [189.73506]]
420 Cost:  8.315314 
Prediction:
 [[152.50871 ]
 [184.19055 ]
 [180.84216 ]
 [199.07204 ]
 [138.97133 ]
 [105.886116]
 [151.95781 ]
 [116.731865]
 [174.96413 ]
 [166.86311 ]
 [144.48996 ]
 [143.69252 ]
 [184.6592  ]
 [150.53252 ]
 [153.02817 ]
 [188.85753

730 Cost:  7.8652153 
Prediction:
 [[152.60513 ]
 [184.19417 ]
 [180.91112 ]
 [199.05614 ]
 [139.02113 ]
 [105.768974]
 [151.84183 ]
 [116.50375 ]
 [174.83012 ]
 [166.52759 ]
 [144.43822 ]
 [143.55696 ]
 [184.82185 ]
 [150.79045 ]
 [152.88478 ]
 [188.78474 ]
 [141.38177 ]
 [183.30626 ]
 [175.75862 ]
 [157.55884 ]
 [177.42668 ]
 [174.74927 ]
 [168.51761 ]
 [149.03142 ]
 [189.80164 ]]
740 Cost:  7.852447 
Prediction:
 [[152.60799 ]
 [184.19434 ]
 [180.9132  ]
 [199.05565 ]
 [139.02272 ]
 [105.76551 ]
 [151.83827 ]
 [116.496765]
 [174.82616 ]
 [166.51753 ]
 [144.43665 ]
 [143.55292 ]
 [184.82677 ]
 [150.79823 ]
 [152.88042 ]
 [188.78261 ]
 [141.39153 ]
 [183.30101 ]
 [175.76424 ]
 [157.5637  ]
 [177.42302 ]
 [174.74695 ]
 [168.51518 ]
 [149.04073 ]
 [189.80363 ]]
750 Cost:  7.839785 
Prediction:
 [[152.6108  ]
 [184.1945  ]
 [180.91524 ]
 [199.05513 ]
 [139.02429 ]
 [105.76206 ]
 [151.8347  ]
 [116.489784]
 [174.8222  ]
 [166.50754 ]
 [144.43507 ]
 [143.54887 ]
 [184.83163 ]
 [150.80598 ]

1110 Cost:  7.4436855 
Prediction:
 [[152.70265]
 [184.20265]
 [180.98357]
 [199.03792]
 [139.08054]
 [105.64983]
 [151.71396]
 [116.25257]
 [174.69397]
 [166.17683]
 [144.38237]
 [143.41655]
 [184.99449]
 [151.06567]
 [152.72931]
 [188.71075]
 [141.72813]
 [183.11678]
 [175.9554 ]
 [157.72893]
 [177.29584]
 [174.6692 ]
 [168.42978]
 [149.35722]
 [189.87343]]
1120 Cost:  7.4341908 
Prediction:
 [[152.70494]
 [184.20291]
 [180.9853 ]
 [199.03746]
 [139.08206]
 [105.64703]
 [151.71078]
 [116.24635]
 [174.69075]
 [166.1684 ]
 [144.381  ]
 [143.4132 ]
 [184.99867]
 [151.07236]
 [152.7255 ]
 [188.709  ]
 [141.7366 ]
 [183.11206]
 [175.96013]
 [157.73302]
 [177.2926 ]
 [174.66731]
 [168.42758]
 [149.36507]
 [189.87523]]
1130 Cost:  7.424767 
Prediction:
 [[152.70723]
 [184.2032 ]
 [180.98705]
 [199.03702]
 [139.0836 ]
 [105.64423]
 [151.70764]
 [116.24015]
 [174.68758]
 [166.16003]
 [144.37964]
 [143.40987]
 [185.00284]
 [151.07903]
 [152.72171]
 [188.70728]
 [141.74506]
 [183.10738]
 [175.9

1490 Cost:  7.129419 
Prediction:
 [[152.7811  ]
 [184.21452 ]
 [181.04465 ]
 [199.02106 ]
 [139.13774 ]
 [105.55333 ]
 [151.60011 ]
 [116.029175]
 [174.58385 ]
 [165.88281 ]
 [144.33379 ]
 [143.30017 ]
 [185.1418  ]
 [151.30202 ]
 [152.59335 ]
 [188.65083 ]
 [142.029   ]
 [182.94667 ]
 [176.12181 ]
 [157.8715  ]
 [177.18031 ]
 [174.60402 ]
 [168.35042 ]
 [149.63211 ]
 [189.93814 ]]
1500 Cost:  7.122326 
Prediction:
 [[152.78293]
 [184.21486]
 [181.0461 ]
 [199.02061]
 [139.1392 ]
 [105.55106]
 [151.59727]
 [116.02364]
 [174.58124]
 [165.87575]
 [144.33258]
 [143.29738]
 [185.14537]
 [151.30775]
 [152.59001]
 [188.6494 ]
 [142.03635]
 [182.94243]
 [176.12581]
 [157.87492]
 [177.17746]
 [174.60246]
 [168.34843]
 [149.63872]
 [189.93974]]
1510 Cost:  7.1152754 
Prediction:
 [[152.78477]
 [184.21523]
 [181.04758]
 [199.0202 ]
 [139.1407 ]
 [105.54881]
 [151.59448]
 [116.01813]
 [174.57867]
 [165.86874]
 [144.3314 ]
 [143.29465]
 [185.14893]
 [151.31349]
 [152.5867 ]
 [188.64803]
 [142.043

1780 Cost:  6.9438453 
Prediction:
 [[152.8302 ]
 [184.22525]
 [181.08475]
 [199.00903]
 [139.17976]
 [105.49247]
 [151.5216 ]
 [115.87533]
 [174.5145 ]
 [165.69098]
 [144.30096]
 [143.22507]
 [185.23958]
 [151.45978]
 [152.5011 ]
 [188.61304]
 [142.23193]
 [182.82857]
 [176.23131]
 [157.96454]
 [177.10127]
 [174.56268]
 [168.29503]
 [149.81259]
 [189.98322]]
1790 Cost:  6.938127 
Prediction:
 [[152.83176]
 [184.22566]
 [181.08604]
 [199.00864]
 [139.1812 ]
 [105.49055]
 [151.51903]
 [115.87027]
 [174.51231]
 [165.68481]
 [144.29991]
 [143.22267]
 [185.24275]
 [151.4649 ]
 [152.4981 ]
 [188.61186]
 [142.23857]
 [182.82468]
 [176.23485]
 [157.96754]
 [177.09868]
 [174.56139]
 [168.29321]
 [149.81844]
 [189.98473]]
1800 Cost:  6.9324756 
Prediction:
 [[152.83328]
 [184.22603]
 [181.08733]
 [199.00822]
 [139.1826 ]
 [105.48863]
 [151.51643]
 [115.86521]
 [174.51012]
 [165.67867]
 [144.29883]
 [143.22028]
 [185.2459 ]
 [151.47   ]
 [152.49507]
 [188.61066]
 [142.24515]
 [182.82077]
 [176.2

### Logistic regression

In [16]:
# Logistic regression은 결과가 0과 1로만 나옴. 따라서 0과 1의 값사이로 추정하여
# 0.5보다 크면 1, 작으면 0으로 분류함

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

# Lab 5 Logistic Regression Classifier
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2],
          [2, 3],
          [3, 1],
          [4, 3],
          [5, 3],
          [6, 2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
# sigmoid는 0과 1사이의 값이 나오도록 하는 함수
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
# logistic regression의 경우에는 cost함수가 y와 y'의 평균이 아니라 cross entropy 함수를 사용
# hyperthesis를 sigmoid함수로 바꾸면 2차 함수모양의 부드러운 cost 곡선이 그려지지 않으므로 이를 부드럽게 펼칠수 있도록 변형함
# e^x을 펼치려면 반대인 log를 씌운다고 생각
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False

#cast는  두번째 인자로 주어진 type올 변환하는 연산자. true는 1, false는 0
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

0 0.803147
200 0.559126
400 0.507446
600 0.476194
800 0.453527
1000 0.435027
1200 0.418852
1400 0.404157
1600 0.390527
1800 0.377741
2000 0.36567
2200 0.354237
2400 0.343385
2600 0.333073
2800 0.323267
3000 0.313935
3200 0.305052
3400 0.29659
3600 0.288526
3800 0.280839
4000 0.273506
4200 0.266508
4400 0.259826
4600 0.253442
4800 0.247338
5000 0.2415
5200 0.235912
5400 0.23056
5600 0.225432
5800 0.220515
6000 0.215797
6200 0.211268
6400 0.206917
6600 0.202734
6800 0.198712
7000 0.194842
7200 0.191115
7400 0.187525
7600 0.184064
7800 0.180726
8000 0.177505
8200 0.174395
8400 0.171391
8600 0.168488
8800 0.16568
9000 0.162965
9200 0.160336
9400 0.15779
9600 0.155324
9800 0.152934
10000 0.150617

Hypothesis:  [[ 0.03121342]
 [ 0.15948294]
 [ 0.30712357]
 [ 0.78035337]
 [ 0.93892485]
 [ 0.97995102]] 
Correct (Y):  [[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]] 
Accuracy:  1.0


In [18]:
# 당뇨병을 예측하는 데이터. 독립변수는 8개, 종속변수는 1개
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

# Lab 5 Logistic Regression Classifier
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)
#결과는 (759, 8) (759, 1)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

#참고
# https://www.kaggle.com에 많은 양의 sample data가 있으니 참고할 것


(759, 8) (759, 1)
0 1.18491
200 0.724872
400 0.648045
600 0.62712
800 0.614815
1000 0.604681
1200 0.595661
1400 0.587502
1600 0.580091
1800 0.573344
2000 0.56719
2200 0.561565
2400 0.556414
2600 0.551688
2800 0.547343
3000 0.543342
3200 0.539649
3400 0.536236
3600 0.533074
3800 0.530142
4000 0.527416
4200 0.52488
4400 0.522515
4600 0.520308
4800 0.518243
5000 0.516311
5200 0.514498
5400 0.512797
5600 0.511197
5800 0.509691
6000 0.508272
6200 0.506933
6400 0.505668
6600 0.504472
6800 0.50334
7000 0.502267
7200 0.50125
7400 0.500284
7600 0.499366
7800 0.498492
8000 0.497661
8200 0.496869
8400 0.496113
8600 0.495392
8800 0.494703
9000 0.494045
9200 0.493415
9400 0.492812
9600 0.492234
9800 0.49168
10000 0.491148

Hypothesis:  [[ 0.45586058]
 [ 0.93212682]
 [ 0.14565991]
 [ 0.95146787]
 [ 0.28958014]
 [ 0.69409388]
 [ 0.94489026]
 [ 0.59093499]
 [ 0.25293615]
 [ 0.51206863]
 [ 0.70204723]
 [ 0.16136122]
 [ 0.24423037]
 [ 0.39493883]
 [ 0.73766434]
 [ 0.50156832]
 [ 0.69177747]
 [ 0.9199876

### Softmax

In [20]:
# softmax의 기본 개념은 output이 n개일때 n개가 모두 0과 1사이의 값을 갖고 합하면 1이되도록 변형하는 함수
# 결국 확률로 나타냄
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
tf.set_random_seed(777)

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]

# output이 3개이면(class가 3개) 3개로 이루어진 2차원 벡터로 생성
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
# logit은 tf.matmul(X, W) + b를 의미함
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss(logistic regression에서의 cost function을 확장한 것
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

    print('--------------')
    # Testing & One-hot encoding
    # a는 각 output의 확률. 합이 1
    # tf.argmax(a, 1)는 중에서 어느위치가 가장 큰가를 나타냄. argmax의 두번쨰 인자는 axis를 나타냄
    # (1은 행(가장 하위 차원)을 나타내고, 0은 열을 나타냄, 2는 더 고차원을 나타냄)
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))
    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))
    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))
    print('--------------')

    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 2.53859
200 0.67655
400 0.568007
600 0.473027
800 0.381503
1000 0.291667
1200 0.237845
1400 0.215804
1600 0.197333
1800 0.181643
2000 0.168163
--------------
[[  2.41187457e-02   9.75874901e-01   6.37693483e-06]] [1]
--------------
[[ 0.72953796  0.26015043  0.01031155]] [0]
--------------
[[  1.87120044e-08   3.61115148e-04   9.99638796e-01]] [2]
--------------
[[  2.41187457e-02   9.75874901e-01   6.37693483e-06]
 [  7.29537964e-01   2.60150433e-01   1.03115458e-02]
 [  1.87120044e-08   3.61115148e-04   9.99638796e-01]] [1 0 2]


In [18]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

# Predicting animal type based on various features
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

nb_classes = 7  # 0 ~ 6

X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])  # 0 ~ 6  shape는 (?, 1)형태의 2차원

Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot (총 클래스 수(7)를 입력해야함)
#단 onehot을 사용할 경우 (?, 1, 7)형태로 1차원을 늘려버림, 따라서 다음과 같이 차원을 하나 축소해야함
print("one_hot", Y_one_hot)

# (?, 1, 7)의 형태를 (?, 7)한차원을 축소함
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print("reshape", Y_one_hot)
print(y_data.flatten())

one_hot Tensor("one_hot_3:0", shape=(?, 1, 7), dtype=float32)
reshape Tensor("Reshape_3:0", shape=(?, 7), dtype=float32)
[0. 0. 3. 0. 0. 0. 0. 3. 3. 0. 0. 1. 3. 6. 6. 6. 1. 0. 3. 0. 1. 1. 0. 1.
 5. 4. 4. 0. 0. 0. 5. 0. 0. 1. 3. 0. 0. 1. 3. 5. 5. 1. 5. 1. 0. 0. 6. 0.
 0. 0. 0. 5. 4. 6. 0. 0. 1. 1. 1. 1. 3. 3. 2. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 6. 3. 0. 0. 2. 6. 1. 1. 2. 6. 3. 1. 0. 6. 3. 1. 5. 4. 2. 2. 3. 0. 0. 1.
 0. 5. 0. 6. 1.]


In [21]:
W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

# Cross entropy cost/loss
# logit과 y값만 가지고 cross entropy를 자동계산하는 함수를 사용(cross entropy수식을 생략함)
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits,
                                                 labels=Y_one_hot)
cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)


#결과를 어느클래스인가를 표시 (0~6까지의 값을 갖는 벡터)
prediction = tf.argmax(hypothesis, 1)
# Y_one_hot을 argmax를 이용하여 다시 0~6의 값으로 변환한 후 prediction과 같은지 비교함
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={
                                 X: x_data, Y: y_data})
            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(
                step, loss, acc))

    # Let's see if we can predict
    pred = sess.run(prediction, feed_dict={X: x_data})
    # y_data: (N,1) = flatten => (N, ) matches pred.shape
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

# flatten은 펼침임. 예를 들어 [[1],[2]]를 [1, 2]의 형태로 변환
# zip은 두개의 임자에서 원소를 각각 하나씩 가져옴(실행해보면 알 수 있음
# 문자열.format()은 따로 공부할 것(printf와 유사)

one_hot Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)
reshape Tensor("Reshape:0", shape=(?, 7), dtype=float32)
Step:     0	Loss: 2.286	Acc: 39.60%
Step:   100	Loss: 0.556	Acc: 85.15%
Step:   200	Loss: 0.349	Acc: 90.10%
Step:   300	Loss: 0.260	Acc: 92.08%
Step:   400	Loss: 0.208	Acc: 95.05%
Step:   500	Loss: 0.174	Acc: 95.05%
Step:   600	Loss: 0.150	Acc: 95.05%
Step:   700	Loss: 0.131	Acc: 98.02%
Step:   800	Loss: 0.116	Acc: 98.02%
Step:   900	Loss: 0.105	Acc: 98.02%
Step:  1000	Loss: 0.095	Acc: 99.01%
Step:  1100	Loss: 0.087	Acc: 99.01%
Step:  1200	Loss: 0.080	Acc: 99.01%
Step:  1300	Loss: 0.074	Acc: 100.00%
Step:  1400	Loss: 0.069	Acc: 100.00%
Step:  1500	Loss: 0.065	Acc: 100.00%
Step:  1600	Loss: 0.061	Acc: 100.00%
Step:  1700	Loss: 0.058	Acc: 100.00%
Step:  1800	Loss: 0.055	Acc: 100.00%
Step:  1900	Loss: 0.052	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[

### learning rate 조절

In [22]:
# 학습데이터와 테스트 데이터의 분리. learning_rate의 변화관찰
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
# learning_rate를 크게 예를 들어 1.5로 잡으면 발산함.
# 아래의 경우는 너무 작아서 진행이 안됨
optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=1e-10).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)


#여기서 부터는 테스트인데 테스트 데이터를 활용(학습 데이터를 사용하면 안됨)
    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 8.6258 [[ 0.41073388 -0.27916163 -0.81230587]
 [ 2.49756479 -0.89281207 -0.10350699]
 [ 0.5577752   0.60501695  0.19115819]]
1 8.6258 [[ 0.41073388 -0.27916163 -0.81230587]
 [ 2.49756479 -0.89281207 -0.10350699]
 [ 0.5577752   0.60501695  0.19115819]]
2 8.6258 [[ 0.41073388 -0.27916163 -0.81230587]
 [ 2.49756479 -0.89281207 -0.10350699]
 [ 0.5577752   0.60501695  0.19115819]]
3 8.6258 [[ 0.41073388 -0.27916163 -0.81230587]
 [ 2.49756479 -0.89281207 -0.10350699]
 [ 0.5577752   0.60501695  0.19115819]]
4 8.6258 [[ 0.41073388 -0.27916163 -0.81230587]
 [ 2.49756479 -0.89281207 -0.10350699]
 [ 0.5577752   0.60501695  0.19115819]]
5 8.6258 [[ 0.41073388 -0.27916163 -0.81230587]
 [ 2.49756479 -0.89281207 -0.10350699]
 [ 0.5577752   0.60501695  0.19115819]]
6 8.6258 [[ 0.41073388 -0.27916163 -0.81230587]
 [ 2.49756479 -0.89281207 -0.10350699]
 [ 0.5577752   0.60501695  0.19115819]]
7 8.6258 [[ 0.41073388 -0.27916163 -0.81230587]
 [ 2.49756479 -0.89281207 -0.10350699]
 [ 0.5577752   0.6050169

In [23]:
# 정규화가 되지 않아 실행되지 않는 예
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

# 일반 파이썬의 2차원 리스트는 인덱싱과 슬라이싱의 연산이 잘 안됨. 이 연산을 하려면 numpy를 이용

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# 2차원 리스트의 인덱싱과 슬라이싱(일반 리스트에서의 2차원 인덱싱과 슬라이싱 공부할 것(근본적으로 불가능한지 테스트)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  5.17783e+10 
Prediction:
 [[-160113.78125 ]
 [-321787.9375  ]
 [-253248.390625]
 [-177679.515625]
 [-209313.25    ]
 [-211069.421875]
 [-193491.4375  ]
 [-246211.734375]]
1 Cost:  5.68877e+25 
Prediction:
 [[  5.32035246e+12]
 [  1.07104153e+13]
 [  8.42549690e+12]
 [  5.90622858e+12]
 [  6.96080558e+12]
 [  7.01939371e+12]
 [  6.43351708e+12]
 [  8.19114593e+12]]
2 Cost:  inf 
Prediction:
 [[ -1.76350248e+20]
 [ -3.55011124e+20]
 [ -2.79274441e+20]
 [ -1.95769910e+20]
 [ -2.30725285e+20]
 [ -2.32667251e+20]
 [ -2.13247589e+20]
 [ -2.71506576e+20]]
3 Cost:  inf 
Prediction:
 [[  5.84536707e+27]
 [  1.17673238e+28]
 [  9.25692858e+27]
 [  6.48905809e+27]
 [  7.64770133e+27]
 [  7.71207073e+27]
 [  7.06837912e+27]
 [  8.99945159e+27]]
4 Cost:  inf 
Prediction:
 [[ -1.93752590e+35]
 [ -3.90043849e+35]
 [ -3.06833382e+35]
 [ -2.15088556e+35]
 [ -2.53493378e+35]
 [ -2.55626973e+35]
 [ -2.34290967e+35]
 [ -2.98298984e+35]]
5 Cost:  inf 
Prediction:
 [[ inf]
 [ inf]
 [ inf]
 [ inf]
 

In [29]:
# 정규화 함수 적용예

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


# 모든 데이터를 0과 1 사이의 값으로 정규화하는 함수(column 별로 별도 처리)
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# very important. It does not work without it.
xy = MinMaxScaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]
0 Cost:  1.00286 
Prediction:
 [[-1.1563046 ]
 [-0.35192668]
 [-0.10960644]
 [ 0.11945659]
 [-0.05849665]
 [-0.05208498]
 [ 0.68384397]
 [ 0.69562775]]
1 Cost:  0.96121 
Prediction:
 [[-1.11584783]
 [-0.31633139]
 [-0.08031249]
 [ 0.14162183]
 [-0.03148848]
 [-0.02627617]
 [ 0.69867599]
 [ 0.70906878]]
2 Cost:  0.922472 
Prediction:
 [[-1.07679677]
 [-0.28208876]
 [-0.05214643]
 [ 0.16291285]
 [-0.00551617]
 [-0.00146741]
 [ 0.71284181]
 [ 0.72185838]]
3 Cost:  0.886428 
Prediction:
 [[-1.0

In [30]:
# 55000개의 mnist 데이터를 테스트. 각 cell은 0과 1 사이의 실수로 구성됨
# mnist 데이터는 tensorflow에서 자동으로 읽어오는 함수들이 존재함
# mnist를 softmax로 실험하기
# epoch와 batch 개념 알기(epoch는 학습 반복횟수를 의미함. batch는 한 학습을 여러개로 나누어(데이타가 많으므로)
# 구별해서 학습할 목적임

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
import random
# import matplotlib.pyplot as plt
tf.set_random_seed(777)  # for reproducibility

from tensorflow.examples.tutorials.mnist import input_data

# Check out https://www.tensorflow.org/get_started/mnist/beginners for
# more information about the mnist dataset
# one_hot형태로 읽어올 것(학습과 테스트 데이터의 라벨 모두)
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

# mnist.train과 mnist.test로 구성. 각각의 원소들을 읽어오는 method가 존재함(mnist는 class임)
# mnist는 테스트용으로 다운받아 곧바로 사용할 수 있도록 class로 구성되어 있으므로
# real 데이터에 대한 실험방법은 별도로 공부해야함

nb_classes = 10

# MNIST data image of shape 28 * 28 = 784
X = tf.placeholder(tf.float32, [None, 784])
# 0 - 9 digits recognition = 10 classes
Y = tf.placeholder(tf.float32, [None, nb_classes])

W = tf.Variable(tf.random_normal([784, nb_classes]))
b = tf.Variable(tf.random_normal([nb_classes]))

# Hypothesis (using softmax)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Test model
# Y는 one hot으로 읽어왔음.
is_correct = tf.equal(tf.arg_max(hypothesis, 1), tf.arg_max(Y, 1))
# Calculate accuracy
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# parameters
training_epochs = 15   #반복할 학습 획수
batch_size = 100  #한번에 학습할 사이즈(사이즈가 매우 클때

with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    # Training cycle
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size) # batch횟수 계산

        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            c, _ = sess.run([cost, optimizer], feed_dict={
                            X: batch_xs, Y: batch_ys})
            avg_cost += c / total_batch  # cost는 평균이니까 다시 그것들의 평균을 구함

        print('Epoch:', '%04d' % (epoch + 1),
              'cost =', '{:.9f}'.format(avg_cost)) # 문자열 format은 따로 공부해야함

    print("Learning finished")

    # Test the model using test sets
    # 원래는 sess.run으로 실행하나 accuracy.eval와 같이 tensor의 eval명령으로 직접 돌릴 수 있음. 같은 의미임
    print("Accuracy: ", accuracy.eval(session=sess, feed_dict={
          X: mnist.test.images, Y: mnist.test.labels}))

    # Get one and predict
    # 하나의 테스트 데이터를 임의로 가져와서 일치하는지 테스트
    r = random.randint(0, mnist.test.num_examples - 1) #난수발생
    # 난수를 이용하여 테스트 집합에서 하나를 가져옴. one_hot으로 읽어왔으므로 다시 argmax로 index알아냄
    print("Label: ", sess.run(tf.argmax(mnist.test.labels[r:r + 1], 1)))
    print("Prediction: ", sess.run(
        tf.argmax(hypothesis, 1), feed_dict={X: mnist.test.images[r:r + 1]}))


Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 cost = 3.022919588
Epoch: 0002 cost = 1.116484131
Epoch: 0003 cost = 0.883347637
Epoch: 0004 cost = 0.772837832
Epoch: 0005 cost = 0.702170937
Epoch: 0006 cost = 0.652574404
Epoch: 0007 cost = 0.615229270
Epoch: 0008 cost = 0.585011465
Epoch: 0009 cost = 0.560052683
Epoch: 0010 cost = 0.539636173
Epoch: 0011 cost = 0.521681937
Epoch: 0012 cost = 0.506098947
Epoch: 0013 cost = 0.492264473
Epoch: 0014 cost = 0.480134355
Epoch: 0015 cost = 0.468773705
Learning finished
Accuracy:  0.8901
Label:  [8]
Prediction:  [8]
<class 'tensorflow.contrib.learn.python.learn.datasets.base.Datasets'>


### deep learning

In [2]:
#단순 softmax만으로는 XOR문제를 해결할 수 없음을 보이는 예제임
#단순 softmax란 하나의 layer로만 학습하는 것임(logistic regression)
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  
learning_rate = 0.1

x_data = [[0, 0],  [0, 1],  [1, 0],  [1, 1]]
y_data = [[0], [1], [1], [0]]

x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run(W))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.706667 [[ 0.59568405]
 [-0.18443802]]
100 0.69661 [[ 0.31462088]
 [-0.10410701]]
200 0.694263 [[ 0.18248653]
 [-0.04150619]]
300 0.693522 [[ 0.10743469]
 [-0.01227241]]
400 0.69328 [[ 0.06409698]
 [ 0.00014049]]
500 0.693197 [[ 0.03876363]
 [ 0.00459609]]
600 0.693167 [[ 0.02375985]
 [ 0.0055069 ]]
700 0.693155 [[ 0.01475255]
 [ 0.00500158]]
800 0.693151 [[ 0.00927122]
 [ 0.00406213]]
900 0.693149 [[ 0.00589116]
 [ 0.00310839]]
1000 0.693148 [[ 0.00378049]
 [ 0.00229391]]
1100 0.693147 [[ 0.00244708]
 [ 0.00165293]]
1200 0.693147 [[ 0.0015958 ]
 [ 0.00117158]]
1300 0.693147 [[ 0.00104727]
 [ 0.00082066]]
1400 0.693147 [[ 0.00069089]
 [ 0.00056985]]
1500 0.693147 [[ 0.00045788]
 [ 0.00039322]]
1600 0.693147 [[ 0.00030449]
 [ 0.00026994]]
1700 0.693147 [[ 0.00020308]
 [ 0.00018463]]
1800 0.693147 [[ 0.00013576]
 [ 0.0001259 ]]
1900 0.693147 [[  9.09318769e-05]
 [  8.56699917e-05]]
2000 0.693147 [[  6.09999079e-05]
 [  5.81878085e-05]]
2100 0.693147 [[  4.09638087e-05]
 [  3.94659837e

In [1]:
# XOR을 예측하기 위한 deep learning
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)
learning_rate = 0.1

x_data = [[0, 0],  [0, 1],  [1, 0],  [1, 1]]
y_data = [[0], [1], [1], [0]]
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

# hidden layer
# [2, 2]에서 앞의 2는 입력의 갯수, 뒤의 두개는 출력의 갯수
# 출력의 갯수란 현재 layer의 노드 수를 의미함. 각 노드의 출력은 1개임
# 노드수가 많은면 wide하다고하는데 일반적으로 노드수는 입력갯수보다 작게함
W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

# output layer
# 앞의 2는 입력변수의 갯수. 앞 layer의 출력과 같아야함
# 뒤의 1은 출력의 갯수. 여기서는 0과 1만을 예측하므로 1임
W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
# 앞 layer의 sigmoid  출력 값인 layer1을 넣어줌
# 마지막 sigmoid의 출력이 hyperthesis가 됨
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

# cost/loss function(출력이 하나이므로 단순 cross entropyt사용)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.753902 [array([[ 0.7988674 ,  0.6801188 ],
       [-1.21986341, -0.30361032]], dtype=float32), array([[ 1.37522972],
       [-0.78823847]], dtype=float32)]
100 0.695844 [array([[ 0.67166901,  0.71368533],
       [-1.29171741, -0.24467792]], dtype=float32), array([[ 1.1212678 ],
       [-0.90971726]], dtype=float32)]
200 0.694039 [array([[ 0.64527303,  0.70460981],
       [-1.31893897, -0.22392061]], dtype=float32), array([[ 1.0992552],
       [-0.895172 ]], dtype=float32)]
300 0.692437 [array([[ 0.64527798,  0.69601005],
       [-1.35297382, -0.20636196]], dtype=float32), array([[ 1.09027696],
       [-0.88092279]], dtype=float32)]
400 0.690805 [array([[ 0.66653317,  0.68915921],
       [-1.39480054, -0.19111179]], dtype=float32), array([[ 1.09085965],
       [-0.86969215]], dtype=float32)]
500 0.688979 [array([[ 0.70635289,  0.68438059],
       [-1.44506621, -0.17811841]], dtype=float32), array([[ 1.10219085],
       [-0.86151755]], dtype=float32)]
600 0.686812 [array([[ 0.7632086

5600 0.0359662 [array([[ 5.74480629,  5.36716652],
       [-5.83591318, -5.04048967]], dtype=float32), array([[ 8.37778664],
       [-7.79377079]], dtype=float32)]
5700 0.0347513 [array([[ 5.76440477,  5.39701986],
       [-5.85647774, -5.07132673]], dtype=float32), array([[ 8.43841457],
       [-7.85934782]], dtype=float32)]
5800 0.0336124 [array([[ 5.78333664,  5.42575932],
       [-5.87637377, -5.10099745]], dtype=float32), array([[ 8.49732208],
       [-7.92287254]], dtype=float32)]
5900 0.0325428 [array([[ 5.80164194,  5.4534564 ],
       [-5.89563751, -5.12957811]], dtype=float32), array([[ 8.55460644],
       [-7.98446655]], dtype=float32)]
6000 0.0315366 [array([[ 5.81935787,  5.48017645],
       [-5.91430616, -5.15713835]], dtype=float32), array([[ 8.61034107],
       [-8.04423904]], dtype=float32)]
6100 0.0305883 [array([[ 5.83651781,  5.50598097],
       [-5.93241215, -5.183743  ]], dtype=float32), array([[ 8.66460991],
       [-8.1022892 ]], dtype=float32)]
6200 0.0296932 [

In [3]:
# wide하고 deep하게 학습. 결과는 같음
# 각 layer의 shape에 주의해야함
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],  [0, 1],  [1, 0],  [1, 1]]
y_data = [[0], [1], [1], [0]]

x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([10, 1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')
hypothesis = tf.sigmoid(tf.matmul(layer3, W4) + b4)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)


0 1.5569 [array([[-0.60164016,  0.89192021,  0.35191226,  0.56761146, -0.99739665,
         0.32676136, -0.0275667 , -0.74284959, -0.95138216, -2.95208597],
       [ 2.14195418,  1.17518973,  0.3820754 , -1.32208002, -0.01911528,
         0.16187686, -3.04041839,  0.2068328 ,  0.36814651, -1.59220243]], dtype=float32), array([[-0.82702488, -0.59083807, -0.91529149, -1.63873768, -0.39875317,
        -0.07010718, -0.62081033, -1.49444103,  0.23517574, -0.91442388],
       [-0.7995736 ,  1.64319766,  0.71563548,  1.86648691, -0.38515177,
         0.40816587, -0.61722082, -0.09925716,  0.27343321, -1.28574586],
       [-0.08891804,  0.20978071, -0.95120919,  0.33139288, -2.07858539,
        -0.48373953,  1.28179991,  0.48855504,  0.47712448,  0.98934746],
       [ 1.07697999,  1.2265451 , -0.79649937, -0.08373559, -0.36422762,
        -0.32580382, -0.06039998,  2.44203186,  0.18790258,  0.51402962],
       [-1.050017  ,  1.10165775, -0.998483  , -0.65370071, -0.05316174,
        -0.3085064

500 0.666439 [array([[-0.60228467,  0.88033879,  0.3314265 ,  0.52319175, -1.03570938,
         0.32436511, -0.0516802 , -0.7443698 , -0.94934559, -2.99095821],
       [ 2.12960649,  1.34372914,  0.34647885, -1.33839929, -0.04124843,
         0.40953588, -3.03977656,  0.24484244,  0.30201772, -1.72673655]], dtype=float32), array([[-0.83681208, -0.57801795, -0.9133839 , -1.59196997, -0.41196501,
        -0.07435045, -0.60508025, -1.48527551,  0.29081112, -0.9305343 ],
       [-0.78311247,  1.64992762,  0.71094888,  1.89338982, -0.38067603,
         0.40667978, -0.61460888, -0.10753676,  0.24095969, -1.29531884],
       [-0.07734109,  0.1971764 , -0.95467257,  0.28025952, -2.07966733,
        -0.51002359,  1.30231571,  0.48395842,  0.55228275,  0.98568738],
       [ 1.09504998,  1.17631388, -0.80177402, -0.27885041, -0.36586308,
        -0.39108983, -0.00948471,  2.42889404,  0.41247839,  0.52338904],
       [-1.05144274,  1.08884811, -0.99854112, -0.73416644, -0.0615776 ,
        -0.356

1100 0.574989 [array([[-0.77078289,  0.97433364,  0.34650722,  0.77938163, -1.04858065,
         0.46230644, -0.18880199, -0.80480427, -0.95565599, -3.39539289],
       [ 2.22769213,  1.732095  ,  0.3853471 , -1.45500326, -0.00914613,
         0.79247469, -3.03735566,  0.28109246,  0.11117797, -2.64507556]], dtype=float32), array([[-0.93874395, -0.58151799, -0.91418076, -1.55335784, -0.46854624,
        -0.11194734, -0.61352414, -1.50957942,  0.47847909, -0.84574121],
       [-0.70641112,  1.66925848,  0.70225674,  2.00845575, -0.36419135,
         0.48849413, -0.60563588, -0.12812439,  0.12594379, -1.29456294],
       [ 0.02772135,  0.17509252, -0.96022177,  0.20109771, -2.05660081,
        -0.51420236,  1.31999695,  0.47085762,  0.55359703,  1.00418174],
       [ 1.33535206,  1.0948714 , -0.80820411, -0.63934666, -0.30309004,
        -0.48284516,  0.03320006,  2.42717147,  0.52544081,  0.55225503],
       [-0.95753819,  1.06247008, -0.99677664, -0.84860218, -0.02712749,
        -0.37

1800 0.217444 [array([[-1.25357747,  0.84376287,  0.89579582,  1.88140321, -1.12130928,
         0.50759017, -0.36981925, -1.61235583, -0.88272792, -4.03679657],
       [ 3.16188574,  2.05047989,  0.68569946, -1.71262574,  0.09712663,
         0.9749617 , -3.03137326,  0.13719285,  0.07354835, -3.75679398]], dtype=float32), array([[ -1.64373589e+00,  -6.01625204e-01,  -9.08778071e-01,
         -1.60590255e+00,  -6.26901209e-01,  -6.01808131e-01,
         -7.60716617e-01,  -1.59262991e+00,   1.46740210e+00,
         -4.19905841e-01],
       [ -9.31555331e-01,   1.67449403e+00,   7.00247705e-01,
          2.11683393e+00,  -3.67687762e-01,   1.83635354e-01,
         -6.99974597e-01,  -1.65393844e-01,   7.21408010e-01,
         -9.51585233e-01],
       [  3.41337814e-04,   1.63231045e-01,  -9.62006330e-01,
          1.47003159e-01,  -2.02603936e+00,  -7.77206898e-01,
          1.25708628e+00,   4.61013854e-01,   1.02799511e+00,
          1.28511548e+00],
       [  1.71420765e+00,   1.05118

2500 0.0282174 [array([[-1.78718698,  0.55975133,  1.10445237,  2.5826087 , -1.35140872,
         0.71232247, -0.41165036, -1.98805094, -0.87660825, -4.34403133],
       [ 3.81292439,  2.13882565,  0.75728607, -2.01228166,  0.03649794,
         1.07303274, -3.0299418 ,  0.20981969,  0.10491155, -4.12829542]], dtype=float32), array([[-2.14145184, -0.61921811, -0.90147281, -1.83077753, -0.75257695,
        -0.90425146, -0.86987501, -1.66100085,  2.05773616, -0.30393559],
       [-1.12057745,  1.67073762,  0.7049377 ,  2.01242805, -0.36590037,
         0.04645707, -0.76288939, -0.20313209,  0.9212417 , -0.85441375],
       [-0.0269241 ,  0.1609809 , -0.95936084,  0.01940266, -2.02665472,
        -0.90180337,  1.20620906,  0.47331992,  1.21716774,  1.41717386],
       [ 1.87686217,  1.04448199, -0.81048203, -1.29269099, -0.23428215,
        -0.97867888, -0.06343435,  2.57393551,  1.43011606,  1.08882165],
       [-0.68397719,  1.08694172, -0.98237729, -0.6932469 ,  0.33562392,
         0.0

3200 0.0116979 [array([[-1.95932996,  0.47306544,  1.14852571,  2.77603769, -1.39930081,
         0.78348464, -0.41861913, -2.06967878, -0.87425351, -4.44109583],
       [ 3.99761796,  2.15965748,  0.79505622, -2.10976815,  0.02903439,
         1.10826719, -3.02967405,  0.23573454,  0.11419104, -4.23398781]], dtype=float32), array([[-2.2876544 , -0.6286363 , -0.89821452, -1.92580891, -0.80251527,
        -0.99307811, -0.9015224 , -1.67565334,  2.23677778, -0.28070444],
       [-1.18105149,  1.66621506,  0.7071647 ,  1.95875442, -0.37135047,
         0.01861283, -0.77899951, -0.21199894,  0.96501297, -0.84193814],
       [-0.03628188,  0.15932943, -0.95836794, -0.03637727, -2.03613639,
        -0.92755914,  1.19216406,  0.48162943,  1.25788367,  1.44779396],
       [ 1.92035949,  1.04356658, -0.80942291, -1.38864791, -0.26618573,
        -1.02828312, -0.0806578 ,  2.60769153,  1.52930224,  1.15822697],
       [-0.6768347 ,  1.0830158 , -0.97840381, -0.65717649,  0.37743172,
         0.0

3900 0.00697359 [array([[-2.05115604,  0.42754894,  1.1707195 ,  2.8764174 , -1.42077148,
         0.82116538, -0.4214626 , -2.1097436 , -0.87256253, -4.4931035 ],
       [ 4.09281063,  2.16860771,  0.81854612, -2.16245008,  0.02679944,
         1.12782383, -3.02950716,  0.25031421,  0.11926992, -4.28964567]], dtype=float32), array([[-2.36333823, -0.63409787, -0.89620179, -1.98147488, -0.83070588,
        -1.04071343, -0.91760206, -1.68251467,  2.33051038, -0.26858473],
       [-1.2129271 ,  1.66334498,  0.70856047,  1.92608666, -0.37457833,
         0.00519523, -0.78670514, -0.21654487,  0.98518366, -0.83696073],
       [-0.04167812,  0.15845904, -0.95780569, -0.07033894, -2.0425148 ,
        -0.94015348,  1.1849097 ,  0.48643535,  1.27753484,  1.46330047],
       [ 1.94261861,  1.04364371, -0.80886692, -1.44301903, -0.28632554,
        -1.05305994, -0.08976213,  2.62636924,  1.58060074,  1.19487822],
       [-0.67394429,  1.08027482, -0.97601831, -0.6336025 ,  0.3991617 ,
         0.

4500 0.00508289 [array([[-2.10455728,  0.40136343,  1.18333483,  2.93394947, -1.43209386,
         0.84296036, -0.4228552 , -2.13216019, -0.87146479, -4.52339268],
       [ 4.14710522,  2.17314053,  0.83330125, -2.19331002,  0.02588227,
         1.13940346, -3.02944827,  0.25899923,  0.12225064, -4.32178545]], dtype=float32), array([[ -2.40659738e+00,  -6.37367666e-01,  -8.94930422e-01,
         -2.01521993e+00,  -8.47591102e-01,  -1.06860340e+00,
         -9.26682889e-01,  -1.68622577e+00,   2.38447857e+00,
         -2.61461943e-01],
       [ -1.23127377e+00,   1.66155660e+00,   7.09451616e-01,
          1.90609574e+00,  -3.76479030e-01,  -2.23572925e-03,
         -7.90885746e-01,  -2.19154760e-01,   9.95959878e-01,
         -8.34497690e-01],
       [ -4.49562371e-02,   1.57971069e-01,  -9.57459271e-01,
         -9.13229808e-02,  -2.04659939e+00,  -9.47202206e-01,
          1.18075562e+00,   4.89317030e-01,   1.28841829e+00,
          1.47210777e+00],
       [  1.95530736e+00,   1.043

5200 0.00381737 [array([[-2.15131354,  0.37865224,  1.19423866,  2.98380685, -1.44136667,
         0.86197168, -0.42392179, -2.15132213, -0.87044978, -4.54992676],
       [ 4.19399643,  2.17674303,  0.84690171, -2.22045946,  0.02523062,
         1.14965105, -3.02944827,  0.26670423,  0.12486926, -4.34977627]], dtype=float32), array([[-2.44402075, -0.64026535, -0.8937543 , -2.04545641, -0.86268502,
        -1.09317553, -0.93447727, -1.68931341,  2.43142748, -0.255126  ],
       [-1.24720645,  1.6599288 ,  0.7102831 ,  1.88815677, -0.37814164,
        -0.00854842, -0.79436833, -0.22142534,  1.0048542 , -0.8325668 ],
       [-0.04791813,  0.15756015, -0.95714629, -0.11034518, -2.05038834,
        -0.95323843,  1.17714822,  0.49188474,  1.29766059,  1.47970796],
       [ 1.96627212,  1.04423046, -0.80825013, -1.50444436, -0.31047589,
        -1.07877922, -0.09965649,  2.64716482,  1.63526976,  1.23456156],
       [-0.67134017,  1.07690787, -0.97318965, -0.60438025,  0.42249581,
         0.

5900 0.00303397 [array([[-2.18781948,  0.36108759,  1.20267367,  3.02239108, -1.44822228,
         0.87677115, -0.42465758, -2.16601157, -0.86963135, -4.57064772],
       [ 4.23018789,  2.17935014,  0.85797602, -2.24173713,  0.02478015,
         1.15771544, -3.02944827,  0.27277127,  0.12691626, -4.37152719]], dtype=float32), array([[-2.47295237, -0.64253926, -0.89279443, -2.06943989, -0.87468225,
        -1.11248004, -0.94046897, -1.69162107,  2.46789813, -0.25008905],
       [-1.25955808,  1.65862691,  0.71096724,  1.8739537 , -0.37943542,
        -0.01336687, -0.7969768 , -0.22319077,  1.01146865, -0.83118945],
       [-0.05029512,  0.15725279, -0.95688897, -0.12556358, -2.05348063,
        -0.95787889,  1.17434561,  0.49391615,  1.30471146,  1.48557782],
       [ 1.97474337,  1.04456425, -0.80801749, -1.52721   , -0.31980455,
        -1.08781743, -0.1032663 ,  2.654845  ,  1.65483809,  1.24894166],
       [-0.67051303,  1.07561016, -0.97209805, -0.59282309,  0.43090934,
         0.

6600 0.00250537 [array([[-2.21760392,  0.34688252,  1.20951366,  3.05364394, -1.45358455,
         0.88881862, -0.42519587, -2.17783546, -0.86895132, -4.58755445],
       [ 4.25944424,  2.18135118,  0.86731642, -2.25914502,  0.02442843,
         1.16433251, -3.02944827,  0.2777459 ,  0.12858649, -4.38920021]], dtype=float32), array([[-2.49637699, -0.64439583, -0.89198399, -2.08921146, -0.88461572,
        -1.12831867, -0.94530201, -1.69344032,  2.49754095, -0.24590747],
       [-1.26957738,  1.65754747,  0.71154863,  1.8622843 , -0.38048753,
        -0.01723508, -0.79903805, -0.22462723,  1.0166626 , -0.8301422 ],
       [-0.05227946,  0.157012  , -0.95667702, -0.1381858 , -2.05610371,
        -0.96162653,  1.17206323,  0.49559036,  1.31036901,  1.4903295 ],
       [ 1.98159671,  1.04489803, -0.80781907, -1.54586935, -0.32761356,
        -1.09506178, -0.10621861,  2.66115046,  1.67065346,  1.26063848],
       [-0.66988069,  1.07453167, -0.97118288, -0.58304209,  0.43773785,
         0.

7300 0.00212658 [array([[-2.24266458,  0.33502758,  1.2152431 ,  3.07978082, -1.45794475,
         0.898938  , -0.42560592, -2.18768215, -0.86837256, -4.60178423],
       [ 4.28387356,  2.18296289,  0.87539274, -2.27382469,  0.02413099,
         1.16992188, -3.02944827,  0.28194422,  0.12999126, -4.40401745]], dtype=float32), array([[-2.51596212, -0.64595395, -0.89128238, -2.10596514, -0.89308029,
        -1.14171302, -0.94933391, -1.69492424,  2.52241182, -0.24233101],
       [-1.27796805,  1.65662968,  0.7120561 ,  1.85243416, -0.38137108,
        -0.02045102, -0.80072731, -0.22583349,  1.02090025, -0.82930851],
       [-0.05398253,  0.1568177 , -0.95649296, -0.14893146, -2.0583601 ,
        -0.96475774,  1.17014253,  0.49701017,  1.31506956,  1.49430358],
       [ 1.98732328,  1.04523182, -0.80765218, -1.56160212, -0.33431888,
        -1.10106719, -0.10871055,  2.66648269,  1.68385208,  1.270455  ],
       [-0.66937888,  1.073614  , -0.97039491, -0.57457089,  0.44345877,
         0.

8000 0.00184285 [array([[-2.2642386 ,  0.32490045,  1.22015882,  3.10216212, -1.46159279,
         0.90763712, -0.42592779, -2.19608712, -0.86787134, -4.61402893],
       [ 4.30476427,  2.18431234,  0.88250792, -2.28648138,  0.0238664 ,
         1.17474949, -3.02944827,  0.28556472,  0.13119955, -4.41674232]], dtype=float32), array([[-2.53273606, -0.64728945, -0.89066654, -2.12046242, -0.90044785,
        -1.15329671, -0.95278186, -1.69617069,  2.54376984, -0.2392052 ],
       [-1.28516185,  1.65583611,  0.71250165,  1.84394729, -0.38213104,
        -0.02319384, -0.80215234, -0.22687049,  1.02445555, -0.8286224 ],
       [-0.0554744 ,  0.15665667, -0.95632607, -0.15826175, -2.06035042,
        -0.96744055,  1.16848552,  0.49824086,  1.31907809,  1.49770904],
       [ 1.99222517,  1.04556561, -0.80749774, -1.57515287, -0.34018749,
        -1.10617268, -0.11086325,  2.67108965,  1.69513202,  1.27888501],
       [-0.66896647,  1.07282043, -0.96970409, -0.56710494,  0.44836542,
         0.

8600 0.00165129 [array([[-2.28057694,  0.31728122,  1.22387421,  3.11904049, -1.4642961 ,
         0.91421878, -0.42615339, -2.20241332, -0.8674919 , -4.6233058 ],
       [ 4.32050419,  2.1853137 ,  0.88799858, -2.29608154,  0.0236571 ,
         1.17841601, -3.02944827,  0.28830993,  0.13211398, -4.42634249]], dtype=float32), array([[-2.54538608, -0.64829755, -0.89018977, -2.13148093, -0.90607929,
        -1.16210496, -0.9553805 , -1.69709444,  2.55991673, -0.23680651],
       [-1.29059267,  1.65523279,  0.71284914,  1.83752251, -0.38270715,
        -0.02525694, -0.80321223, -0.22765517,  1.02709377, -0.82812107],
       [-0.05662084,  0.15653871, -0.95619661, -0.16537218, -2.06188798,
        -0.96946657,  1.16723275,  0.49917817,  1.32209063,  1.50027978],
       [ 1.99591935,  1.04585171, -0.80739045, -1.58541095, -0.34469089,
        -1.11000061, -0.11249924,  2.67459464,  1.70362365,  1.28525853],
       [-0.66866553,  1.07221735, -0.96917546, -0.5613448 ,  0.45207095,
         0.

9300 0.00147069 [array([[-2.2976377 ,  0.30937508,  1.22774625,  3.1365962 , -1.467062  ,
         0.92108554, -0.42637074, -2.20898342, -0.86709523, -4.63299847],
       [ 4.33686686,  2.18631673,  0.89382762, -2.30611467,  0.02342719,
         1.18225205, -3.02944827,  0.29117727,  0.13306801, -4.43635225]], dtype=float32), array([[-2.55855012, -0.64934468, -0.88968271, -2.14301944, -0.91200918,
        -1.17133701, -0.95808327, -1.69804537,  2.57675362, -0.23427095],
       [-1.2962482 ,  1.65460002,  0.71322101,  1.83082175, -0.38330767,
        -0.0273995 , -0.80430579, -0.22847381,  1.02980149, -0.82761145],
       [-0.05783392,  0.15641944, -0.95607144, -0.17283303, -2.06352258,
        -0.97157729,  1.16592336,  0.50016248,  1.32522011,  1.5029577 ],
       [ 1.99976325,  1.04612958, -0.80726528, -1.59611249, -0.34944704,
        -1.11396039, -0.11421354,  2.67826438,  1.71244383,  1.29190171],
       [-0.66836166,  1.07158542, -0.96861386, -0.55523449,  0.45593014,
         0.

10000 0.00132412 [array([[-2.31293941,  0.30232832,  1.23121774,  3.15228558, -1.46950281,
         0.92723984, -0.42654949, -2.21485138, -0.86673921, -4.64168167],
       [ 4.35148668,  2.18719935,  0.8991406 , -2.3151257 ,  0.02320883,
         1.1856972 , -3.02944827,  0.29374966,  0.13392295, -4.44531727]], dtype=float32), array([[-2.57031655, -0.65027779, -0.88922364, -2.15339065, -0.91737276,
        -1.17964888, -0.96049976, -1.69888198,  2.59183478, -0.23196791],
       [-1.30130982,  1.65402067,  0.7135548 ,  1.82482123, -0.38384774,
        -0.02931228, -0.80527186, -0.22920765,  1.03218818, -0.82716936],
       [-0.05893638,  0.156317  , -0.95594627, -0.179554  , -2.06502461,
        -0.97346807,  1.16473806,  0.50104839,  1.32801247,  1.50535333],
       [ 2.00319719,  1.04637992, -0.80714011, -1.60569859, -0.35375929,
        -1.11748171, -0.11575726,  2.68156719,  1.72031331,  1.2978518 ],
       [-0.66809982,  1.07100809, -0.96810269, -0.54967207,  0.45938319,
         0

### NN의 개선

In [4]:
# 단순 softmax를 이용한 mnist 인식 정확도 측정
# (다음 코드부터는 이를 개선한 내용이 들어감
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
import random
from tensorflow.examples.tutorials.mnist import input_data
tf.set_random_seed(777)  # reproducibility

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
# Check out https://www.tensorflow.org/get_started/mnist/beginners for
# more information about the mnist dataset

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

# input place holders
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])

# weights & bias for nn layers
W = tf.Variable(tf.random_normal([784, 10]))
b = tf.Variable(tf.random_normal([10]))

hypothesis = tf.matmul(X, W) + b

# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=hypothesis, labels=Y))

# GradientDscent optimizer 보다 통상 Adam이 좋다고 알려져있음
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# initialize
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(mnist.train.num_examples / batch_size)

    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        feed_dict = {X: batch_xs, Y: batch_ys}
        c, _ = sess.run([cost, optimizer], feed_dict=feed_dict)
        avg_cost += c / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning Finished!')

# Test model and check accuracy
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print('Accuracy:', sess.run(accuracy, feed_dict={
      X: mnist.test.images, Y: mnist.test.labels}))

# Get one and predict
r = random.randint(0, mnist.test.num_examples - 1)
print("Label: ", sess.run(tf.argmax(mnist.test.labels[r:r + 1], 1)))
print("Prediction: ", sess.run(
    tf.argmax(hypothesis, 1), feed_dict={X: mnist.test.images[r:r + 1]}))


Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 cost = 5.512054557
Epoch: 0002 cost = 1.717794442
Epoch: 0003 cost = 1.150608121
Epoch: 0004 cost = 0.912758181
Epoch: 0005 cost = 0.777680396
Epoch: 0006 cost = 0.690108692
Epoch: 0007 cost = 0.626683580
Epoch: 0008 cost = 0.579149503
Epoch: 0009 cost = 0.542380533
Epoch: 0010 cost = 0.512348814
Epoch: 0011 cost = 0.487698800
Epoch: 0012 cost = 0.467149031
Epoch: 0013 cost = 0.449557352
Epoch: 0014 cost = 0.434459412
Epoch: 0015 cost = 0.420767955
Learning Finished!
Accuracy: 0.8923
Label:  [0]
Prediction:  [0]


In [5]:
# mnist를 여러  layer를 갖는 NN으로 구축
# 이전에 비해 개선된 점(deep하게, Lelu이용, Adamoptimizer이용)

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
import random
# import matplotlib.pyplot as plt

from tensorflow.examples.tutorials.mnist import input_data

tf.set_random_seed(777)  # reproducibility

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
# Check out https://www.tensorflow.org/get_started/mnist/beginners for
# more information about the mnist dataset

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

# input place holders
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])

# weights & bias for nn layers
# 256개의 노드를 갖는 첫째 hidden layer
W1 = tf.Variable(tf.random_normal([784, 256]))
b1 = tf.Variable(tf.random_normal([256]))
# sigmoid보다 lelu를 이용함. backpropagation할때 deep할수록 점점 약해지는 것을 방지
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)

# 2번째 hidden layer
W2 = tf.Variable(tf.random_normal([256, 256]))
b2 = tf.Variable(tf.random_normal([256]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)

W3 = tf.Variable(tf.random_normal([256, 10]))
b3 = tf.Variable(tf.random_normal([10]))
hypothesis = tf.matmul(L2, W3) + b3

# define cost/loss & optimizer
# 마지막은 lelu를 쓰면 안된고 반드시 softmax를 활용해야함
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=hypothesis, labels=Y))

# Optimizer를 Adam을 사용하면 더 개선됨
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# initialize
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(mnist.train.num_examples / batch_size)

    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        feed_dict = {X: batch_xs, Y: batch_ys}
        c, _ = sess.run([cost, optimizer], feed_dict=feed_dict)
        avg_cost += c / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning Finished!')

# Test model and check accuracy
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print('Accuracy:', sess.run(accuracy, feed_dict={
      X: mnist.test.images, Y: mnist.test.labels}))

# Get one and predict
r = random.randint(0, mnist.test.num_examples - 1)
print("Label: ", sess.run(tf.argmax(mnist.test.labels[r:r + 1], 1)))
print("Prediction: ", sess.run(
    tf.argmax(hypothesis, 1), feed_dict={X: mnist.test.images[r:r + 1]}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 cost = 170.402600268
Epoch: 0002 cost = 41.581194434
Epoch: 0003 cost = 25.616804798
Epoch: 0004 cost = 17.859852076
Epoch: 0005 cost = 12.841553388
Epoch: 0006 cost = 9.567163741
Epoch: 0007 cost = 7.132143949
Epoch: 0008 cost = 5.285280767
Epoch: 0009 cost = 3.905830099
Epoch: 0010 cost = 2.957957568
Epoch: 0011 cost = 2.054112584
Epoch: 0012 cost = 1.466971759
Epoch: 0013 cost = 1.149025915
Epoch: 0014 cost = 0.827710601
Epoch: 0015 cost = 0.746691486
Learning Finished!
Accuracy: 0.9419
Label:  [7]
Prediction:  [7]


In [6]:
# Initialization and Dropout
# 이전 예제의 overfitting을 방지하기 위해 dropout을 적용
# 마지막 단을 제외하고 lelu후에 dropout을 적용하는데 통상 학습을 할때는 0.5~0.7정도만 keep함
# 단, 실전 또는 테스팅할때는 반듯히 1로 설정해야함. 따라서
# L1 = tf.nn.dropout(L1, keep_prob=keep_prob)의 keep_prob을 placeholder로 만들고
# 학습과 테스팅할때마다 변경
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
import random
# import matplotlib.pyplot as plt

from tensorflow.examples.tutorials.mnist import input_data

tf.set_random_seed(777)  # reproducibility

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
# Check out https://www.tensorflow.org/get_started/mnist/beginners for
# more information about the mnist dataset

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

# input place holders
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])

# dropout (keep_prob) rate  0.7 on training, but should be 1 for testing
keep_prob = tf.placeholder(tf.float32)

# weights & bias for nn layers
# http://stackoverflow.com/questions/33640581/how-to-do-xavier-initialization-on-tensorflow
W1 = tf.get_variable("W1", shape=[784, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b1 = tf.Variable(tf.random_normal([512]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L1 = tf.nn.dropout(L1, keep_prob=keep_prob)

W2 = tf.get_variable("W2", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b2 = tf.Variable(tf.random_normal([512]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L2 = tf.nn.dropout(L2, keep_prob=keep_prob)

W3 = tf.get_variable("W3", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b3 = tf.Variable(tf.random_normal([512]))
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
L3 = tf.nn.dropout(L3, keep_prob=keep_prob)

W4 = tf.get_variable("W4", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b4 = tf.Variable(tf.random_normal([512]))
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)
L4 = tf.nn.dropout(L4, keep_prob=keep_prob)

W5 = tf.get_variable("W5", shape=[512, 10],
                     initializer=tf.contrib.layers.xavier_initializer())
b5 = tf.Variable(tf.random_normal([10]))
hypothesis = tf.matmul(L4, W5) + b5

# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# initialize
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(mnist.train.num_examples / batch_size)

    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        feed_dict = {X: batch_xs, Y: batch_ys, keep_prob: 0.7}
        c, _ = sess.run([cost, optimizer], feed_dict=feed_dict)
        avg_cost += c / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning Finished!')

# Test model and check accuracy
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print('Accuracy:', sess.run(accuracy, feed_dict={
      X: mnist.test.images, Y: mnist.test.labels, keep_prob: 1}))

# Get one and predict
r = random.randint(0, mnist.test.num_examples - 1)
print("Label: ", sess.run(tf.argmax(mnist.test.labels[r:r + 1], 1)))
print("Prediction: ", sess.run(
    tf.argmax(hypothesis, 1), feed_dict={X: mnist.test.images[r:r + 1], keep_prob: 1}))



Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 cost = 0.461017369
Epoch: 0002 cost = 0.171008974
Epoch: 0003 cost = 0.129878603
Epoch: 0004 cost = 0.107183706
Epoch: 0005 cost = 0.093973142
Epoch: 0006 cost = 0.085986843
Epoch: 0007 cost = 0.077588860
Epoch: 0008 cost = 0.072418443
Epoch: 0009 cost = 0.065901595
Epoch: 0010 cost = 0.061425260
Epoch: 0011 cost = 0.056515421
Epoch: 0012 cost = 0.055606571
Epoch: 0013 cost = 0.047081190
Epoch: 0014 cost = 0.049906666
Epoch: 0015 cost = 0.046359510
Learning Finished!
Accuracy: 0.9812
Label:  [3]
Prediction:  [3]
